### ISSUE TITLE
[Fluxstore] - Registration and Maps question

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#1010]
Hi,

I would like apply some changes in the App:

a. How can I remove Google Maps?
b. I would prefer to remove some lines from 'Registration Form'. Here they are:
    
         1. Last name
         2. Country
         3. State
         4. City
         5. Street name
         6. Zipcode
c. How can I enable logining by phone like in demo?

Thanks

**Comment by minhcasi** [comment]
Hi, could I know which the product that you are mention about?

Also, please provide us your purchased screenshot - thanks

**Comment by Pars1vaLl** [comment]
Hi,

It is Fluxstore App.

Here is my Purchase Code: https://user-images.githubusercontent.com/45024483/63820143-9af0e500-c961-11e9-8005-114a7ac9e36b.png

Thanks

**Comment by minhcasi** [comment]
a. you can use the Flutter inspect to quickly locate the map widget and remove it, to know how to use the inspector ref to - https://www.youtube.com/watch?v=JIcmJNT9DNI

b. We suggest not to remove these fields as it is required for the WooCommerce API to complete the billing address, otherwise, you need to hard code these fields, again use the inspector to know to locate code for removing. 

c. pls check this blog for the SMS guide - https://medium.com/@inspireui/announcing-fluxstore-1-2-1ffe497d0f60
