### ISSUE TITLE
[MStore Pro] - Stripe Issues

### ISSUE THREAD

**Issue by stefanue** [inspireui/support#1053]
1. My issue

Can't use stripe gateway as presented here:
Payment demo: [Video Link](https://www.youtube.com/watch?v=6hNz43oTyUA)
[Docs reference](https://docs.inspireui.com/mstore/getting-started/)

instead of a that flow, app is opening a webview (that is generating your cart is empty)

2. Screenshots

<img width="437" alt="Screen Shot 2019-09-12 at 6 00 48 PM" src="https://user-images.githubusercontent.com/5262617/64800713-567f5f00-d587-11e9-9281-66bfce985d4a.png">

3. My screenshot of the purchase product or my comment:

![Screen Shot 2019-09-12 at 6 02 18 PM](https://user-images.githubusercontent.com/5262617/64800813-83337680-d587-11e9-9634-e4e86a97fa74.png)

**Comment by minhcasi** [comment]
@stefanue the native stripe payment is removed from v3.0 due to some limitation we change it to Webview payment for more security and more flexible work with multi-payment gateway.

To fix the empty 404 payment please follow this guide - https://docs.inspireui.com/mstore/questions/#404-error-page-when-process-the-payment-

You can also use native stripe payment by install this library - https://github.com/tipsi/tipsi-stripe - 

Thank you!

**Comment by stefanue** [comment]
Hello @minhcasi thanks for your quick reply. Is there a way you can share v3.0. zip with me, so i can wire up the native checkout?

Currently there is a` index_stripe.js` under `src/containers/cart`, but it's calling two components `<StripePanel />`  and `<PaypalPanel />` that don't exist in the project.

**Comment by minhcasi** [comment]
Hi, could you share your email here

**Comment by stefanue** [comment]
@minhcasi of course, its `stefanue@gmail.com`

**Comment by stefanue** [comment]
Hi @minhcasi, I didn't get anything on my email

**Comment by minhcasi** [comment]
Hi, i've sent the link to your email :)
