### ISSUE TITLE
[Flux News] - 

### ISSUE THREAD

**Issue by amit81** [inspireui/support#1092]
[common.zip](https://github.com/inspireui/support/files/3638458/common.zip)

Hi,

I have purchased fluxnews, But i am getting an error with our Wordpress blog site when we add your default URL its working perfectly. Can you please tell me do i have to add any plugin in our Wordpress ?

We are not getting data in app home page. In the category, we are getting listing but when we refresh it will show error: type’_internalLinkedHashMap<sting. dynamic>’ is not a subject of type ‘iterable<dynamic>’

Waiting for your reply Thanks

> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue

2. Screenshots

3. My screenshot of the purchase product or my comment:

3. Config files (optional)

**Comment by minhcasi** [comment]
hi, you can download and active from resource/Wordpress-extension (from the download package) - thank you!

**Comment by amit81** [comment]
Hi

As per your guideline, we already have done active plugins. The issue is not short out. So please guide us ...

Thanks...

**Comment by minhcasi** [comment]
@amit81 - we are going to update new 1.1 and will keep you an update. 

Do you mind to share your config file so that we could have a quick test!

**Comment by amit81** [comment]
[common.zip](https://github.com/inspireui/support/files/3647881/common.zip)

Hi, 

As per your requirement config file, please find attachment before also I send to you ... please short out the issue 

Thanks,

**Comment by minhcasi** [comment]
noted and checking, thank you!

**Comment by amit81** [comment]
hi, 

Any Update?

**Comment by minhcasi** [comment]
@amit81 - we will release the new v1.1 and testing your issue on Monday - thank you!

**Comment by dttrung26** [comment]
Dear @amit81 ,

after checking your problem, we have figured out the issue is in onLoadMore function. To be specific, your Wordpress API will return an error message if we request an unavailable page. For example, if we request for posts by category on page 1, that works perfectly but when it comes to page 2, it will raise an error (as attached below picture) instead of returning an empty array for posts as expected 
![image](https://user-images.githubusercontent.com/32586676/65856152-05df7280-e38b-11e9-91b4-a132800fb4ea.png)

Please double-check and update your Wordpress version in order to fix this. We would be glad to hear from you. 

Cheers,
Trung.

**Comment by Chizinski** [comment]
Any solution for this yet?

**Comment by amit81** [comment]
Hi,

As per your suggestion Wordpress version.

we  already check everything and everything  is updated so no issue from our side so please guide to us 

Thanks 

Amit
