### ISSUE TITLE
[Beonews] 'RCTOneSignalExtensionService' issues

### ISSUE THREAD

**Issue by simomed13** [inspireui/support#126]
<img width="1011" alt="capture d ecran 2018-12-23 a 21 02 31" src="https://user-images.githubusercontent.com/26978992/50387181-aadf6780-06f6-11e9-9e52-4c633d928454.png">

**Comment by minhcasi** [comment]
Hi, could you help to format the ticket and provide more detail info so that we can understand more about the issue, example: you purchased code, product... 

This solution could be related, please help to check - https://beonews.inspireui.com/faq-and-troubleshooting#fix-cfbundleidentifier-does-not-exist

Thank you!
