### ISSUE TITLE
[Mstore Expo] - Add custom Attributes in Checkout Page 

### ISSUE THREAD

**Issue by rmsoftengine** [inspireui/support#1280]
Hello,
I have purchased the product from envato. I am having difficulties with the following things.
1. I have additional custom fields in my woo commerce (text, radio button, time picker) how can I amend those in the checkout page. Currently its not working.

2. Having difficulties with login and registration with the latest updates

Could someone please help me in priority basis as I am really stuck for last few days.
![image](https://user-images.githubusercontent.com/22434913/67490907-eecf3000-f66b-11e9-8720-bf5de8b2d057.png)

I have purchased this only few weeks ago
Thanks
Rashed

**Comment by minhcasi** [comment]
Hi Rashed,

To customize the checkout field  you need to customize the checkout form from the payment as well - pls refer to this file locate from the mstore-api - https://github.com/inspireui/mstore-api/blob/master/templates/mstore-api-template.php

Could you share what is your issues with the login so that we could help 

Thank you!
