### ISSUE TITLE
[MStore MV] - Not showing vendors in  wp-json /v1/stores - API

### ISSUE THREAD

**Issue by lukasprelovsky** [inspireui/support#1337]
Hi, (my previous topic was arbitrarily closed by your moderators, and the problem was not solved!)
https://github.com/inspireui/support/issues/1253 . I send keys to support mails.

My problem:

    I need call api http://mstore.io/wp-json/mstore/v1/stores

(/v1/stores) for api listing vendor stores (url for live web https://barfer.sk/wp-json/mstore/v1/stores )

    In demo url not working API stores

    Purcharse code - 9c050d9d-7583-47a4-a550-2785b43cf91d

Please help me. Thx

**Comment by minhcasi** [comment]
@lukasprelovsky  - try to use the API that provide from the plugin that you are using

Example if you using Dokan use this https://wedevsofficial.github.io/dokan/#stores

Or: /wp-json/wcfmmp/v1/store-vendors if using - https://wordpress.org/plugins/wcfm-marketplace-rest-api/

The mstore.io is not use for the Multi Vendor demo so that the link above will not work
