### ISSUE TITLE
[FluxNews] - (ASK) About Post Detail Layout

### ISSUE THREAD

**Issue by bakpaorabbit** [inspireui/support#1343]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets 
> - After creating an issue, please copy the URL to the Product link on http://codecanyon.net - to help us know you have purchased our product (example: https://tppr.me/DJA8L)
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue : Where I can set the post detail as in the following picture. because I didn't find the documentation. 

2. Screenshots : https://prnt.sc/ptfi6t

3. My screenshot of the purchase product or my comment: https://prnt.sc/po3gph

3. Config files (optional) : default config

**Comment by dttrung26** [comment]
Hi @bakpaorabbit , 
sorry for the late response. In order to change type of blog detail, please take a look at kAdvanceConfig. All you need to do is changing the value for "DetailBlogLayout" into kBlogLayout.oneQuarterImageType, kBlogLayout.fullSizeImageType or kBlogLayout.halfSizeImageType. 

const kAdvanceConfig = {
  "IsRequiredLogin": false,
  "GuestCheckout": true,
  "EnableShipping": false,
  "GridCount": 3,
  "DetailedBlogLayout": kBlogLayout.oneQuarterImageType,  // <= change this one //
  "EnablePointReward": false,
  "HeartButtonType": kHeartButtonType.cornerType,
};

Happy coding!
