### ISSUE TITLE
[flexstore] - COD order goto to pending status

### ISSUE THREAD

**Issue by ramyragab1** [inspireui/support#1400]
1. when i do new order in COD order goto to pending status  
and  this status not send any mail to tell me new order arrived 
when i do any order from web  didn't found any error this error show when i send order from app 

2. https://www.dropbox.com/s/so7vtviffg474nc/Screen%20Shot%202019-11-16%20at%203.15.17%20AM.png?dl=0

3. My screenshot of the purchase product or my comment:https://www.dropbox.com/s/h9n4hmy218dof84/Screen%20Shot%202019-11-15%20at%206.32.01%20PM.png?dl=0

**Comment by minhcasi** [comment]
@ramyragab1 - as this is the limitation of the woocommerce API - https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order - once you using the CDO, there is only status set_paid true/false, the app is using false so that the order status will be processing, so you can monitor from the website to update the processing to next step or change it to another status.

if you set as the true / it will display as completed status - and also send the email

**Comment by ramyragab1** [comment]
ok i want to set it to true 
tell me how 
if i set it to true order goto processing or completed
i want to make order processing

**Comment by minhcasi** [comment]
@ramyragab1 - pls try to update this line of code - https://tppr.me/YLScv

**Comment by ramyragab1** [comment]
not working mate !

**Comment by minhcasi** [comment]
@ramyragab1 

Could you try to update the function.php from WP site

```
add_filter( 'woocommerce_cod_process_payment_order_status', 'change_cod_payment_order_status' );
function change_cod_payment_order_status( $order_status, $order ) {
	return 'processing';
}
```

**Comment by ramyragab1** [comment]
not fixed mate 
i add this code in themes function.php

**Comment by minhcasi** [comment]
Let me check with another solution, thank you!

@vumanhsn97  - pls help for further investigating

**Comment by vumanhsn97** [comment]
@ramyragab1 Try to change file lib/screen/checkout/payment.dart like 
[payment.dart.zip](https://github.com/inspireui/support/files/3895322/payment.dart.zip). Run app and send me your feedback

**Comment by ramyragab1** [comment]
not fixed 
soory for late replay
