### ISSUE TITLE
Can i use my wordpress theme and make app like my wordpress theme?

### ISSUE THREAD

**Issue by ashe2020** [inspireui/support#1433]
Hi, 
I don't know how to convert my website to app by using fluxnews, can you share a documentation more detailed? In fact, i just want that i can custom a no internet page, like the webpage is not available, and keep everything else entirely like my wordpress theme?  Does it possible?
I don't know how to make screenshot to show that i bought the plugin.
Best,

**Comment by minhcasi** [comment]
@ashe2020 - first please install some required plugins for the Wordpress - https://docs.inspireui.com/fluxnews/getting-started/#4-install-requires-plugins

Then open the config to change the config point to your website - https://docs.inspireui.com/fluxnews/getting-started/#5-setup-fluxnews

You may need to setup Flutter so that could delivery the app to app stores - https://docs.inspireui.com/fluxnews/getting-started/#1-setup-flutter-envoriment
