### ISSUE TITLE
[Fluxstore] - bugs and improvements

### ISSUE THREAD

**Issue by louissaad24** [inspireui/support#1455]
- Facebook messenger bug in smart chat:
This format isnt working in debug mode (maybe it works in release mode)  fb-messenger://user/{user-id}
But the working one is https://m.me/{userid}
- Bug in the cart
when i am in debug mode and i add products to the cart then the cart shows the products then whwn i chekout i close the app then reopen it it still shows the items in the cart ( even if i do not close the app) the only way to remove the items is to clear the cart. The cart must be automatically cleared when user chekout.
- Bug in purchase list:
When the user makes an order, we update the status of the order in wordpress to pricessing or refunded or delivered or anything, but the status doesnt change in the app.
- Bug :
Please fix the blog post because when we implement the blog in the code as shown in the documentation nothing works. 
Even if i open it from the side bar it shows nothing. 
- Recent view isnt working also. The recently viewed producta doeant show.
Thank you for listening to us - Louis Saad - 

[move feature request to Trello]

**Comment by minhcasi** [comment]
@louissaad24 - thank you for the detailed feedback, i've assigned to the team checking and will let you know

**Comment by louissaad24** [comment]
Thank you so much.

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Forcing the user to update the app](https://trello.com/c/Q3TEcms6/1-forcing-the-user-to-update-the-app)

**Comment by vumanhsn97** [comment]
@louissaad24 
- Facebook messenger bug: I dont know your bug. Smart chat using deep link so we support in whatsapp, tel, sms. If you want to use others, you need to enter right deep link.
- Bug in the cart: I checked but I dont find your bug. Make sure you checkout successful and return order detail. If you receive order and cart is not empty, you can give me some screenshot or video demo.
- Bug in purchase list: Fixed it in next version. You can get new status when refresh.
- Bug in blog: Fixed it in next version
- Recent view is not working: Fixed in next version. Recent view just show when you see more than 3 products detail.
Thanks your issues!!!

**Comment by louissaad24** [comment]
@vumanhsn97  Thank you so much i will test these feature and tell you about any new bugs and cool features.

**Comment by minhcasi** [comment]
@louissaad24 - thank you Louis - let us know if you have any further request support - very best!
