### ISSUE TITLE
fluxstore failed to build ios #1495

### ISSUE THREAD

**Issue by nizarweb77** [inspireui/support#1544]
sorry for the late sir
this is my rdp imac
https://mega.nz/#!ZcoTAIrQ!-zFIfCz0HdPAGHEVxVmgtRhVLrdNyrGOwYgFId-8hxQ
you will find the user name and the password my rdb have high connection will be fast for you and strong rdp .
i have put my work in android studio alerday
so my problem is the firebase for android not working i alerday add to the android folder and for the ios i put the .plist file of the firebase in the desktop please fix for me with the build problem
i will appreciate what you will do sir

**Comment by minhcasi** [comment]
@nizarweb77 could you share proof of purchase screenshot from http://codecayon.net/downloads

And clarify more about your issues as we not quite understand. Could you able to run the Test Drive successful https://flutter.dev/docs/get-started/test-drive ?

**Comment by nizarweb77** [comment]
![{0F68468F-94AF-4502-B851-5EF028CDDBF9} png](https://user-images.githubusercontent.com/57265062/70345778-11548b80-185d-11ea-93f1-697eeb91ce7d.jpg)
i open the ticket before two day and now you tell me give me pof what is this oh sir you alerday ask me about my teamviewer *fluxstore failed to build ios (#1495)* and now i give you my rdp plz don't tell me go and read because there is no solution of it i have problem in the build plus the firebase that is all can you fix it ?

**Comment by minhcasi** [comment]
Sorry for the inconvenience - as we suggest to create one ticket for your issues so that we know your previous issues.

Regarding your current issue - could I check if you downloaded the google service file and override for your project? related docs - https://docs.inspireui.com/fluxstore/firebase/ - this is important step to integrate with your own firebase.

Also, please share the screenshot of the issue so that we could understand more your problem - thank you!

**Comment by nizarweb77** [comment]
i send you my rdp in mega but there is no help this not good support
