### ISSUE TITLE
[EvaStore] - My orders not showing

### ISSUE THREAD

**Issue by sohilchauhan** [inspireui/support#162]
- Product: EvaStore - Shopify mobile store by React Native and GraphQL
 - Your Purchased Code: aef7ca61-4f5a-4778-9e64-fa677e068071

When customer is logged in, they are not seeing orders in My orders section,
Although in Shopify they can see all orders.
But in app, Its showing 
"You don't have any orders"

Can you look into this as soon as possible please?

**Comment by minhcasi** [comment]
Hi Sohil, could you share your common/config.js file - thank you!

**Comment by sohilchauhan** [comment]
Thanks for the quick response.
Find attached config file.

 Config.js
<https://drive.google.com/file/d/13lG37K_Iyp15GJ-Jp54J95dudWpUT2CM/view?usp=drive_web>

**Comment by luyx2412** [comment]
Hi @sohilchauhan Can you provide me the example user account which have any orders via luyxtran264@gmail.com

Thanks

**Comment by sohilchauhan** [comment]
Just sent email.

**Comment by luyx2412** [comment]
Hi @sohilchauhan , i found the reason. 
1. In `services/GraphqlAPI/index.js` file ==> line `831` in `getOrders` function. 
2. Replace `product: formatProduct(c.variant.product),` with `product: formatProduct(c.variant ? c.variant.product : null)`. 

Because some your product do not variant, so i lack of check condition for this case.

<img width="948" alt="screen shot 2019-01-08 at 2 04 08 pm" src="https://user-images.githubusercontent.com/8909619/50815039-4c4cf700-134e-11e9-8e55-1feadcbfe18d.png">


Thanks

**Comment by sohilchauhan** [comment]
Okay. I want to show details to customers on each order without going to check order status. So it should be clear which items are in order. 
So expand is fine. Can you tell me which fixes i need to do to expand order details when clicking Show detail?

**Comment by luyx2412** [comment]
HI @sohilchauhan Now expand order showed, so the easiest way to resolve this problem is hide `Show detail` button.
1. In `containers/MyOrdersContainer/index.js`
2. comment or remove code line `144` follow the image

<img width="671" alt="screen shot 2019-01-08 at 2 42 02 pm" src="https://user-images.githubusercontent.com/8909619/50816619-ae5c2b00-1353-11e9-9efe-e08dfbc0638d.png">

Thanks.

**Comment by sohilchauhan** [comment]
I understood. But is there not any way to show order details expanded with all items in that order?

**Comment by luyx2412** [comment]
Hi @sohilchauhan Now the order item showed with full items, only collapse function do not work. So you can hot fix with hide the button `Show detail`.

Thanks
