### ISSUE TITLE
BlurView.ios.js: Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by absmugz** [inspireui/support#17]
![screenshot 2018-11-15 at 22 30 46](https://user-images.githubusercontent.com/2528692/48580620-60651100-e928-11e8-834f-586475a52a9a.png)
**Required Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)

**Describe the bug**

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.
If possible please share your config.js that use for the app setting

**Comment by minhcasi** [comment]
Can you try this solution:
- Remove the node_module and Run script: yarn cache clean && yarn install
- Remove the Expo client app on the simulator & run script: expo start

Please explain more detail the ticket on next time instead of show the image that help we understand more on your issue 

Thanks

**Comment by EffectiveOG** [comment]
same issue for me (i bought via envato yesterday my account effectiveog ) , https://www.useloom.com/share/06224e6612b843d6b2b793d43db959a0
