### ISSUE TITLE
[mstro EXPO] - RTL not works on 3.9.7 (last ver)

### ISSUE THREAD

**Issue by kiamoz** [inspireui/support#1852]
Dear support you said if I use new ver RTL issue will solve but when I change the Constants.js => rtl :true 
nothing change in app , I reset the simulator and run fresh app on it but not works !

**Comment by luyx2412** [comment]
Hi @kiamoz 
Please change filed `Language: ar`, because currently we based on the language to switch RTL. And uninstall and reinstall app again. The app  cached with persist, so you need uninstall app to remove old cache.
![image](https://user-images.githubusercontent.com/8909619/72658078-a7dca680-39de-11ea-8845-9bc1365d515c.png)

P/S: Feel free to reopen the issue.

Thanks

**Comment by kiamoz** [comment]
@luyx2412  Hello dear , but not works! I changed   lang too I clear  simulator . but not work ,could you connect me with teamviwer  today ?
