### ISSUE TITLE
[Fluxstore] - Cant change home style and main colour.

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#1911]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: i did everything but still i'm failed in changing main color and changing the home desing with my new one.

2. Screenshots issues: 
![Screenshot_2020-01-23-19-05-24-155_com celkart store](https://user-images.githubusercontent.com/59877416/72991569-3787b800-3e18-11ea-8d6f-1bfd19bd9b1c.jpg)

3. Proof of my purchased:
![Screenshot (32)](https://user-images.githubusercontent.com/59877416/72991692-70c02800-3e18-11ea-8971-8ec73a131e31.png)

3. Config files (optional)
[config.zip](https://github.com/inspireui/support/files/4103482/config.zip)

**Comment by Saifahmad99** [comment]
Any updates guys?

**Comment by MrRishb** [comment]
Same problem I try to  change categories

**Comment by brax1989** [comment]
I had this problem too

the solution:

In the project / lib / common folder we will find the files:

config.dart
config.json (original file)
config_ar.json
config_en.json
config_en.json
config_ja.json
........
.......
........

the configuration of the config.json file is copied to the rest of the files that follow with config_ar.josn, config_es.josn, etc.

These files correspond to the language, so if we only configure config.json and then select another language, it will look for the language in the rest of the files so we must copy the configuration in the rest so that we can see the changes reflected.

I hope it is useful.

regards.
