### ISSUE TITLE
[fluxnews] - Need a Guide

### ISSUE THREAD

**Issue by devienguilde** [inspireui/support#1959]
Hello there, it's awesome purchase but i got some question cuz i'm newbie here can u guys kindly help me?
oh right here's my Proof of my purchased:
https://prntscr.com/qus1tn

**My issue:**
1. How to “Tip: to quickly show the category ID, go to lib/models/category.dart and print the return categories object from return JSON” print this so i can see category?

2. at customization are we just add those code ? any video or guide how to do it?

3. where ads settings?

4. how to use Full Webview only so i can put membership page only (“plugin ultimate membership pro”) so after login they can press button to see membership page

5. how to hide side drawer i want to made my news portal like this (https://play.google.com/store/apps/details?id=com.cnbc.indonesia&hl=in)

6. How to Change Layout? i mean like other widget u guys didn't give guide for changing Blog Views, header, footer, and ads positioning

**Comment by dttrung26** [comment]
Hello @devienguilde ,
please kindly follow those instructions to fix your issues. If you still encounter any difficulty, please let me know: 

1. In lib/models/category.dart, copy and replace the existing getCategories function in CategoryModel by this function to see your categories. Or you can see your category id by entering this URL http://[enter-your-site-here]/wp-json/wp/v2/categories (installing Json Format or Json View could make those data visible by human eyes)

void getCategories({lang}) async {
    try {
      categories = await _service.getCategories(lang: lang);
      isLoading = false;
      message = null;
      for (Category cat in categories) {
        categoryList[cat.id] = cat;
      }
      print(categories);
      notifyListeners();
    } catch (err) {
      isLoading = false;
      message =
          "There is an issue with the app during request the data, please contact admin for fixing the issues " +
              err.toString();
      notifyListeners();
    }
  }

2. Yes, basically. Currently, we haven't provided customizing guide yet. But still, you can do it by following this guide: https://docs.inspireui.com/fluxnews/customization/ to determine what kind of layout you want to put into your homepage, then place those code into config.json file located in lib/common. Btw, there is an existing template config.json file in common folder, please try to simulate it. 

3.  Advertisement configuration is located /lib/common/config.dart file, it is at the end of the file to be specific (kAdConfig). 

4. For this customizing, you can create a button and assign onTap function linking to WebView flutter widget which assigned your membership page. 
- For how to create a button, please take a look at this docs: https://flutter.dev/docs/development/ui/widgets/material#Buttons 
- For how to use WebView flutter widget, please refer this: https://pub.dev/packages/webview_flutter#-readme-tab-

5.  To hide side drawer, please replace my file into your /lib/widgets/blog/logo.dart file. 
[logo.zip](https://github.com/inspireui/support/files/4132525/logo.zip)

6.  To change blog view, in config.dart file located at /lib/common, please change "DetailedBlogLayout" value to kBlogLayout.oneQuarterImageType, kBlogLayout.halfSizeImageType or kBlogLayout.fullSizeImageType depending on your interest. 

Finally, so sorry for the lack of necessary customizing docs for customers. We will be working on adding that. Stay tuned!

Have a nice day,
Trung.

**Comment by devienguilde** [comment]
Thank you for answering this question kind sir,
Heres my new question about this code :
1. How to add button at footer layout i mean the menu that at buttom layers
2. I wonder why theres cart future ist sneek peek for next updated, if its true so awesome
3. Is there a way to custom home page i mean like i add a view button there that goes to webview?

Regards,
Nyaroon

**Comment by dttrung26** [comment]
Hi Nyaroon @devienguilde ,

1. We are sorry to say that adding a new tab into a tab bar function(or adding a new button into the bottom layer like what you said)  is not available at the moment. We will try to bring it in the next update.

2. Cart function is not suitable for reading-news-app. As a result, I'm afraid that this function won't be added to Flux News sir. 

3.  If you really want to add a button navigating to a WebView, please refer to this file 
[index.zip](https://github.com/inspireui/support/files/4133250/index.zip) by replacing it into your /lib/widgets/blog.

**Comment by devienguilde** [comment]
Alright Last Question sir:
How to make Banner Slide Image Full Screen ?

**Comment by dttrung26** [comment]
Good morning @devienguilde ,
Here come your answers: 
1. If you want to make your Banner Slider Image displayed in full screen, please replace this file in your /lib/widgets/blog/banner but I highly recommend not sir because of the asynchronous padding in your UI app.
[devienguilde_customer.zip](https://github.com/inspireui/support/files/4137507/devienguilde_customer.zip)

2 + 3 + 6. Please make sure all your configurations in config.json are perfectly done, if so, I can make sure that your app could still be customized fine. Currently, I know it's still hard for non-tech users to follow and customize our app due to the lack of some critical parts in our docs. However, our technical team is working on a FluxBuilder which is a drag-and-draw tool to build an app as what you wish. It will be expected to be released in the next few months. Meanwhile, we are still working on improving our docs. Please be sympathetic and stay tuned with us. 

4. After having requested, all of your users would go to https://[enter-your-site-here]/wp-admin/users.php. Please take a look. 

5. Unfortunately, Flux News still doesn't have this feature, sir. 

If you are satisfied with FluxNews and support services, please review/rate us at https://codecanyon.net/item/fluxnews-fluxnews-flutter-mobile-app-for-wordpress/reviews/24569377  And if you could state my name as your supporter, it would be very very very nice sir xD

Have a nice day,
Trung.

**Comment by devienguilde** [comment]
Tankyou sir

**Comment by devienguilde** [comment]
the no.1 is not work sir

**Comment by dttrung26** [comment]
Hi @devienguilde ,
please try again with this file. Sorry I forgot to save my change xD 
[banner_items.zip](https://github.com/inspireui/support/files/4157299/banner_items.zip)

Happy coding sir!

**Comment by devienguilde** [comment]
Alright thankyou, but how to made the header to be sticky?

**Comment by dttrung26** [comment]
Hi @devienguilde ,

if you want to customize Flux News, please contact support@inspireui.com and state clearly your requirements for the appropriate customizing service sir. 

Have a nice day!
