### ISSUE TITLE
[EvaStore] - console.log is disabled by default in the native debugger

### ISSUE THREAD

**Issue by satyavh** [inspireui/support#1997]
See issue #1971 #1953

First of all you are not reading my issue, for the 2nd time already. 

I had found the problem already after the first issue, it is caused by you / your codebase. Yet you keep coming with incorrect support.

To enable console.log: `Constansts.js`
set `useReactotron: false`

So the question is why you are shipping code that has console.log disabled by default in the native debugger? And why are you not aware of that?

**Comment by inspireui-support** [comment]
@satyavh - we support 2 types of debugger for the app, the Reactotron is enabled as default so that it is disabled the console.log
- Reactotron: https://github.com/infinitered/reactotron
- React native debugger: https://github.com/jhen0409/react-native-debugger

you can change to react native debugger by update common/constants.js 
```
  useReactotron: false
```

Let us know if you have any questions - thank you :)
