### ISSUE TITLE
[FLUX NEWS] - Categories names not showing  

### ISSUE THREAD

**Issue by sharkcrypto92** [inspireui/support#2006]
Categories names not showing when i make Default language "ar 

  {
      "layout" : "sliderList",
      "type" :"imageOnTheRight",
      "name": {
        "en": "محلية",
        "ab": "محلية",
        "vi": "محلية"
      },
      "category": 2

**Comment by sharkcrypto92** [comment]
![Screenshot_1580800398](https://user-images.githubusercontent.com/42117836/73752051-4869ef00-4771-11ea-971b-062803d1607c.png)

**Comment by dttrung26** [comment]
Hi @sharkcrypto92 ,
please send me your common folder to check. Thanks!

**Comment by sharkcrypto92** [comment]
https://workupload.com/file/3w4uGLSf

**Comment by dttrung26** [comment]
Please replace your common folder with this and tell me if it works.
Nice day!
[sharkcrypto92_customer.zip](https://github.com/inspireui/support/files/4157383/sharkcrypto92_customer.zip)

**Comment by sharkcrypto92** [comment]
![Screenshot_1580878090](https://user-images.githubusercontent.com/42117836/73811925-f31ef380-47eb-11ea-923f-dc38ed50f9d1.png)


its worked thanx

one more thing before i publish my app 

can i enable comment with no sign up or sign in required ?

if i cant how i  hide add comment on posts  ??

i would love it i can make users comment with no sign in

**Comment by dttrung26** [comment]
Hi @sharkcrypto92 ,
Signing is a must when commenting because wordpress user needs identification to approve/deny comment. If it's still annoying, you can turn comment section off by replacing those files in your /lib/widgets/blog/detailed_blog. 

[sharkcrypto92.zip](https://github.com/inspireui/support/files/4162956/sharkcrypto92.zip)

If you are satisfied with Fluxnews as well as our support services, a review/rate for us at https://codecanyon.net/item/fluxnews-fluxnews-flutter-mobile-app-for-wordpress/reviews/24569377 would be appreciated, mate. 

Nice day btw!
