### ISSUE TITLE
FluxNews - Menu icon does not appear

### ISSUE THREAD

**Issue by danimmg** [inspireui/support#2035]
The menu icon is not showing, what do I have to do to make it appear?

Thanks

![Capture06-02-2020-17 35 43](https://user-images.githubusercontent.com/59834619/73977908-fad4ba00-4909-11ea-8533-3d8756c84985.jpg)

![Capture06-02-2020-17 36](https://user-images.githubusercontent.com/59834619/73977911-fb6d5080-4909-11ea-9fb7-51510edf62c6.jpg)

![Capture06-02-2020-17 37](https://user-images.githubusercontent.com/59834619/73977914-fc05e700-4909-11ea-9ddd-1fc8f2e32fe7.jpg)

**Comment by inspireui-support** [comment]
Hi @danimmg - as we could not see your username from the proof screenshot, could you give the comment on this link - https://codecanyon.net/item/fluxnews-fluxnews-flutter-mobile-app-for-wordpress/24569377 ? Thanks

**Comment by danimmg** [comment]
> 
> 
> Hi @danimmg - as we could not see your username from the proof screenshot, could you give the comment on this link - https://codecanyon.net/item/fluxnews-fluxnews-flutter-mobile-app-for-wordpress/24569377 ? Thanks
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/6f4c995d1bce0962274142058b60b437a7fdfe51/68747470733a2f2f73332e656e7661746f2e636f6d2f66696c65732f3237313230393833322f69636f6e2d38302e706e67">CodeCanyon**[FluxNews - Flutter mobile app for Wordpress](https://codecanyon.net/item/fluxnews-fluxnews-flutter-mobile-app-for-wordpress/24569377)**
> > - Version: 1.2.2 
> > - Last update: 02/02/2020 
> > - Files Included: Full Working App Source Code
> > - This is Exclusive Product Licence from Envato.
> > ```
> > FluxNews is an app that does magic for yo...</div></blockquote>
> > ```

![Capture06-02-2020-22 30 23](https://user-images.githubusercontent.com/59834619/73993890-5d41b080-4932-11ea-995d-0bedd61fc47a.jpg)

**Comment by dttrung26** [comment]
Good morning @danimmg , 
please send me your /lib/common folder so that I can take a look. 
Have a nice day btw!

**Comment by danimmg** [comment]
Good morning
[common.zip](https://github.com/inspireui/support/files/4170326/common.zip)

**Comment by danimmg** [comment]
Another error appeared
I would like to duplicate some sections but when I do this by clicking on the news the screen goes black

**Example**
--------------------------------------------------------
   {
      "layout" : "threeColumn",
      "type" :"",
      "name": {
        "en": "Últimas notícias",
        "ar": "Recent Recipe",
        "vi": "Recent Recipe"
      },
      "category": 51
    },
    {
      "layout" : "threeColumn",
      "type" :"",
      "name": {
        "en": "Últimas notícias",
        "ar": "Recent Recipe",
        "vi": "Recent Recipe"
      },
      "category": 209
    },
------------------------------------------------------
![Capture07-02-2020-09 32 11](https://user-images.githubusercontent.com/59834619/74031018-39f91e80-498f-11ea-9575-bb1d38b327ed.jpg)

**Comment by dttrung26** [comment]
Good morning @danimmg ,
![image](https://user-images.githubusercontent.com/32586676/74117488-65c41080-4bea-11ea-8f09-748915f44f9d.png)

In order to enable Drawer Menu which is number 1 in the attached image, please coppy my zip file then replace in your /lib/widgets/blog. To customize app menu logo with yours, please update in kLogoImage located at /lib/common/constants.dart (don't forget to upload your logo image at as
[danimmg_customer.zip](https://github.com/inspireui/support/files/4178738/danimmg_customer.zip)

For the last issue, the navigation turns to blank space because your 2 categories "51" and "209" return the same blog, which leads to duplicate id Hero Animation. You can add as many duplicate layouts as you want, just make sure every blog id is unique within the app. 

Have a nice day,
Trung.
