### ISSUE TITLE
FluxNews - does not show videos of the post

### ISSUE THREAD

**Issue by danimmg** [inspireui/support#2055]
**1 - When a post has a youtube video it doesn't show in the app**

**2 - In this problem the menu is working but I can't find where I change its icon because the icon is not readable**
https://github.com/inspireui/support/issues/2035#issuecomment-583934527

**3 - Translation**
I'm not able to translate these terms

![Capture10-02-2020-15 01 58](https://user-images.githubusercontent.com/59834619/74176424-68d4f600-4c16-11ea-8852-be4a42c9526f.jpg)

------------------------

![Capture10-02-2020-15 00 38](https://user-images.githubusercontent.com/59834619/74176440-71c5c780-4c16-11ea-9bdf-83d29cfba09f.jpg)

### 4 - banner autoplay
The autoplay function on the banner  "design": "default", is not working

{
      "layout": "bannerImage",
      "isSlider": true,
      "design": "default",
      **"autoPlay": true,**
      "showBackGround": true,
      "radius": 4.0,
      "height": 0.3,

Thanks

**Comment by dttrung26** [comment]
Hi @danimmg ,
1. Currently, video blogs are just supported in one quarter blog type only. You, therefore, need to change your app's detailed blog type in "DetailedBlogLayout": kBlogLayout.oneQuarterImageType in kAdvanceConfig located at /lib/common/config.dart
2. To change your app header logo, please update asset link at kLogoImage variable located at /lib/common/constants.dart
3. This error will be fixed in the next version. Thanks for notification sir.
4. Banner Image in Flux News is not able to support autoPlay feature at the moment sir.

Have a nice day!
