### ISSUE TITLE
flux news

### ISSUE THREAD

**Issue by Alqumairi** [inspireui/support#2062]
1- Google Login Error

The google login is working and register successfully. however, its not appearing in the firebase console. see the screenshots provided

![Annotation 2020-02-11 145222](https://user-images.githubusercontent.com/37410069/74216070-34c50800-4cde-11ea-9c1b-b8ac2ccd1b4c.png)
![Annotation 2020-02-11 145205](https://user-images.githubusercontent.com/37410069/74216072-368ecb80-4cde-11ea-93c1-6d9224157456.png)

2- the app icon is not changing, I have changed the icon and also run the code you given in the emulator but it did not change. see the screenshot provided 

![Annotation 2020-02-11 145525](https://user-images.githubusercontent.com/37410069/74216253-c2085c80-4cde-11ea-8aaf-ad03d8f2f2c6.png)
![Annotation 2020-02-11 145546](https://user-images.githubusercontent.com/37410069/74216255-c3398980-4cde-11ea-9a2f-1e2ba8befc74.png)
![Annotation 2020-02-11 145634](https://user-images.githubusercontent.com/37410069/74216257-c46ab680-4cde-11ea-9f3a-59d2e8965755.png)

3- I need to know how to do the push notifications with one signal , i have linked it and added the secure key and the id but it did now work. any advice how to to do that? 

Thanks

**Comment by Alqumairi** [comment]
Hello

**Comment by Alqumairi** [comment]
Hi, 

How to do the post notification in the app?, please help

**Comment by Alqumairi** [comment]
Hello, 

Good Morning

**Comment by Alqumairi** [comment]
Helllllllllllllo, 

Please answer me asap

**Comment by Alqumairi** [comment]
That's really waste of time

**Comment by dttrung26** [comment]
Hi @Alqumairi ,
1. Google Login currently has issue and it will be fixed in the next version 1.3. 
2. Follow those steps to configure your app icon: 
 + Upload your app icon in /assets/images/[your-app-icon-here]
 + Update your path asset in: 

```
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/[your-app-icon-here]"
```

+ Run "flutter pub get" 
+ Exit your app and run it again. 

3. After correctly integrate your app with OneSignal, there's 2 simple ways to push notification to your users: 
 - Notify your users with a new push message (https://documentation.onesignal.com/docs/sending-notifications)
- Notify users when you either post a new blog or edit existing blog by ticking push notification box
![image](https://user-images.githubusercontent.com/32586676/74411331-89e35400-4e6d-11ea-8d76-791582742794.png)

Hope this helps

**Comment by Alqumairi** [comment]
2- I have done everything you said, but it still not changing 
3- I have done this as well but its not working as well

**Comment by Alqumairi** [comment]
Please answer me fast because im getting headache due to delays

**Comment by Alqumairi** [comment]
`OneSignal.shared.init(
  "your_onesignal_app_id_here",
  iOSSettings: {
    OSiOSSettings.autoPrompt: false,
    OSiOSSettings.inAppLaunchUrl: true
  }
);
OneSignal.shared.setInFocusDisplayType(OSNotificationDisplayType.notification);`

this code from one signal , I have added the dependencies and everything except this code i dont know where to put it.   this is the link fro their guide 

https://documentation.onesignal.com/docs/flutter-sdk-setup

**Comment by dttrung26** [comment]
Hi sir, please contact me via skype: dttrung.ityu for further assistance. Thanks for your cooperation.

**Comment by dttrung26** [comment]
Solved via skype
