### ISSUE TITLE
Connect website to tool (BeoNews Pro ) #2059

### ISSUE THREAD

**Issue by nahuelbourdichon** [inspireui/support#2172]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
I can't use my product  someone close the previous tiket and didn't solved my issue
2. Screenshots issues:

3. Proof of my purchased:

3. Config files (optional)

**Comment by dahmsh** [comment]
Peace be upon you, the app was purchased because it is excellent and I liked it
It was purchased and now I need to link to the website and upload in Google Play and Apple Store I have no developer
https://prnt.sc/r5pde0
seejad.com

**Comment by dahmsh** [comment]
I have accounts in Google Play Apple Store paid, approved and ready to be uploaded

**Comment by inspireui-support** [comment]
@dahmsh - please help to provide your all requirement to support@inspireui.com - and request the installing service support, we may not support for all the project at this time due to the team available, but we will notify if the project is met with the team capacity.

We use this github ticket to support the technical issues during the installing - thank you!
