### ISSUE TITLE
[fluxstore] - 

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#2356]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue: I Just wanted to know how could I update the new version of the flux store with my old one. Do I have to edit everything on new updated code or is there is anything that can be done easily because editing everything from color to home screen and config data is pretty hard?

2. Screenshots issues (required):

3. Proof of my purchased (required):
![Screenshot (32)](https://user-images.githubusercontent.com/59877416/76702784-a5eb4700-66f2-11ea-8a85-8cf79b847dc2.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@Saifahmad99 - you can submit the form to request access to our Gitlab so that you can know which files have been changed - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform

This is the big updated with a lot of files and features improvement. If you have customized the app, you can keep your project and only override some new features from 1.6.5 like Search Filter... Please also check this guide for the detail explain - https://medium.com/@inspireui/announcing-fluxstore-1-6-337efff1791f
