### ISSUE TITLE
[Fluxstore - multi vendors] - error building app for app store

### ISSUE THREAD

**Issue by abd096** [inspireui/support#2478]
Hello, 

I am trying to build the app for app store but getting the following error:

Error message: https://prnt.sc/rosecl

Purchase code: https://prnt.sc/r03dpe

**Comment by minhcasi** [comment]
@abd096 - could you try to use some solution here - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by abd096** [comment]
Hello @minhcasi i actually try it but didnt work with me, do you have any paid service to help me upload the app to app store ?

**Comment by minhcasi** [comment]
@abd096 - please check this XCode migration you are using latest XCode 11.4  - https://flutter.dev/docs/development/ios-project-migration

Sorry we may not support the paid support at this time, but we will open this services on next 1-2 week, please share your email and detail website URL so that the team could contact to process for futher process - our email support@inspireui.com - thank you!

**Comment by minhcasi** [comment]
@abd096 - please help to send detail requirement to support@inspireui.com - our technical team will contact you for the paid support in 1-2 weeks - thank you!
