### ISSUE TITLE
[Fluxstore] - wooCommerce Variation Default values, Price, Product Name, Filter, Carousel

### ISSUE THREAD

**Issue by IbrahimHd** [inspireui/support#2532]
1. My issue:
  I'm using v1.6.5c
  A.  Product Price shows the "lowest" price rather than a "range".
  B. Product Page: "Add to cart" and "Buy Now" button remains active while the "variations" are not yet loaded. This allows the customer to add a product with "empty" variations and wrong price. Suggested solution: lock the buttons, with adding loading indicator, until the variations are loaded.
  C.  Product Filter: the price range doesn’t work and the values (amounts) do not reflect the maximum product price. For example, it allows for max 1,000 but the existing prices are above this.
  D.  How can a customer "Reset" the filter?
  E.  Product name: how can we allow for longer name (or more than 1 line)?
  F. I sat "EnableReview": false but it still shows reviews. How can I disable it?
  G.  Carousels do not appear as they carousels.  How can we add some indications like: Arrows, or Dots, or horizontal scroll?

2. Screenshots issues (required):
![image](https://user-images.githubusercontent.com/16100897/78261228-a57ee880-7507-11ea-9eec-1d9ff14d0fba.png)
![image](https://user-images.githubusercontent.com/16100897/78261245-ab74c980-7507-11ea-8d9c-4082b96aa3c9.png)
![image](https://user-images.githubusercontent.com/16100897/78261256-af085080-7507-11ea-929c-aadd73892315.png)
![image](https://user-images.githubusercontent.com/16100897/78261270-b3346e00-7507-11ea-875f-ae63a2ec115d.png)

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/16100897/78261377-d65f1d80-7507-11ea-88fd-3402c8f644e9.png)

3. Config files (required)

[config.dart.txt](https://github.com/inspireui/support/files/4421670/config.dart.txt)
[config_en.json.txt](https://github.com/inspireui/support/files/4421671/config_en.json.txt)

**Comment by minhcasi** [comment]
@IbrahimHd - thank you for your suggestion - we will double check the issue and get back you shortly

**Comment by alicankarakus** [comment]
im checking this subject. the same problem for me

**Comment by trunghieuvn** [comment]
Hi @alicankarakus , we are checking, I will respond to you as soon as I solve the problem. Please wait for me. 
Thanks

**Comment by alicankarakus** [comment]
new update and this error: 
![errors](https://user-images.githubusercontent.com/6725793/78361979-f521ea80-75c1-11ea-9f7b-3c73a9b32de1.PNG)

**Comment by IbrahimHd** [comment]
Dear @alicankarakus thank you for taking care for resolving the issues I raise above. Hope you consider addressing ALL of them (A, B, C, D, E, F, G).
It's appreciated if you can come up with the solution before the weekend!
Regards,
Ibrahim

**Comment by trunghieuvn** [comment]
Hi @IbrahimHd , your problems are as follows:

`A. Product Price shows the "lowest" price rather than a "range".`
-> I checked and it works fine. I don't know if I'm misunderstanding, please video of the steps to create this error so I can handle it quickly.

`B. Product Page: "Add to cart" and "Buy Now" button remains active while the "variations" are not yet loaded. This allows the customer to add a product with "empty" variations and wrong price. Suggested solution: lock the buttons, with adding loading indicator, until the variations are loaded.`
-> We will check and update this issue soon. Thank you.

`C. Product Filter: the price range doesn’t work and the values (amounts) do not reflect the maximum product price. For example, it allows for max 1,000 but the existing prices are above this.`
-> You can change the price range by changing the value of the `kMaxPriceFilter` variable in file `lib/common/constants/slider.dart`. The min price will default to 0, the max will take the value of the `kMaxPriceFilter` variable.

`D. How can a customer "Reset" the filter?`
-> This feature will be updated soon. Thank you for the suggestion.

`E. Product name: how can we allow for longer name (or more than 1 line)?`
-> You can increase the line limit of the product name. Search for them in file `lib/widgets/product/product_card_view.dart` , search for the keyword `item.name` and change the `maxLine` limit.

`F. I sat "EnableReview": false but it still shows reviews. How can I disable it?`
-> `EnableReview` has the effect of enabling and disabling review in the checkout feature, not in the card product. This is the default feature of the product, we do not recommend deleting them. If you do not need them, you can delete them in file `lib/widgets/product/product_card_view.dart` (this is not recommended).

`G. Carousels do not appear as they carousels. How can we add some indications like: Arrows, or Dots, or horizontal scroll?`
-> We will update this feature shortly. Thank you.

Please provide more information on problem A.
Thanks so much for your feedback.
Things like this will make us better.

**Comment by trunghieuvn** [comment]
> new update and this error:
> ![errors](https://user-images.githubusercontent.com/6725793/78361979-f521ea80-75c1-11ea-9f7b-3c73a9b32de1.PNG)

Hi @alicankarakus , please create a new ticket and provide the necessary information so we can best support you. 
Thanks very much.

**Comment by alicankarakus** [comment]
A. Product Price shows the "lowest" price rather than a "range".
-> I checked and it works fine. I don't know if I'm misunderstanding, please video of the steps to create this error so I can handle it quickly.

This answer is not working. Maybe woocommers is OK but Opencart is not working.

**Comment by IbrahimHd** [comment]
Hi @trunghieuvn,
Thank you for your reply.

Going throught the mentioned points:
A.  I mean the price range in the products list/grid screen but not in the single product screen.
B. Hope you give this PRIORITY as it's really essential.
C. It would be great if the max price is captured automatically based on the listed products. (especially if there are multiple currencies, as the rate might be 2000x)
D. Looking for adding "filter reset" in the coming up version.
E. Thank you. I'll give it a try.
F. It will be awesome if you can add an "option" for show/hide "reviews". It's need especially when the app is very fresh and has no reviews yet.
G. Looking forward to an improved Carousel in the next update.

Thank you in advance for your support.
Ibrahim

**Comment by IbrahimHd** [comment]
@trunghieuvn, your support please, exspecially for point A.

**Comment by minhcasi** [comment]
@trunghieuvn

**Comment by minhcasi** [comment]
@IbrahimHd - pls help to create one ticket for your all issues to help us focus better on the investigating issue - kindly move to this same ticket #2555

We are trying out best with the support but for some extra customization, we need to review if the feature is useful we will consider to add it to next release - thank you for your time so far.

**Comment by IbrahimHd** [comment]
Hi @minhcasi,
I'm just looking for an answer for issue A:
In product listing screen, why variable products show the "lowest" price rather than a range [lowest-highest]? (first screenshot above)

**Comment by trunghieuvn** [comment]
hi @IbrahimHd , with the F issue, you can fix the following:

You can handle it this way, hide it if the rating is not there (because the minimum score is 1, so we check null or 0 for the case without a rating)

- In file `lib/common/config/general.dart`, add a new field is `hideEmptyProductListRating`
![image](https://user-images.githubusercontent.com/19247680/79721579-ca979780-830c-11ea-9280-4a94a620f307.png)

- in file : `lib/widgets/product/product_card_view.dart` and find the code with keyword: `SmoothStarRating`
![image](https://user-images.githubusercontent.com/19247680/79721553-bfdd0280-830c-11ea-9b6e-e0c90f270663.png)


```
 if (kAdvanceConfig['hideEmptyProductListRating'] == false || (item.ratingCount != null && item.ratingCount > 0))
 SmoothStarRating(
    allowHalfRating: true,
    starCount: 5,
    rating: item.averageRating ?? 0.0,
    size: starSize,
    color: theme.primaryColor,
    borderColor: theme.primaryColor,
    label: Text(
      item.ratingCount == 0 || item.ratingCount == null
          ? ''
          : '${item.ratingCount}',
      style: TextStyle(
        fontSize: ratingCountFontSize,
      ),
    ),
    spacing: 0.0),
```

If the hideEmptyProductListRating flag is false, the application will still show a review if the product has no reviews (like the old logic is there).
If the hideEmptyProductListRating flag is true, the application will hide that product if it has no reviews. (still showing reviews for rated products)

**Comment by trunghieuvn** [comment]
> Hi @minhcasi,
> I'm just looking for an answer for issue A:
> In product listing screen, why variable products show the "lowest" price rather than a range [lowest-highest]? (first screenshot above)

Would you please check if your api returns the highest or lowest price? I guess it may be returning the lowest price.

**Comment by IbrahimHd** [comment]
Hi @trunghieuvn,
I'm no longer check this issue as it's strangely closed by minhcasi.
**issue A**: it return the lowest by default but I'm implementing an "action" to return the highest and it works well in FluxStore. However, my question is why it's not displaying a RANGE [lowest-highest] just as it's displayed in woo (I'm talking about "product listing", not "single product screen")
**Issue F**: `hideEmptyProductListRating` is not exist in v1.6.6b. May in it's in v1.7.1, I'll check it.

Thanks
