### ISSUE TITLE
FluxNews - in app comments are not working. HELP ME!!!!

### ISSUE THREAD

**Issue by zemeister23** [inspireui/support#2546]
1. My issue:
In my application android cannot creating any comment. But in my site i can leave comment
2. Screenshots issues (required):
It say successfuly added post please waiting. but nothing!!!!!!!!
3. Proof of my purchased (required):
<img src="https://i.ibb.co/yXZ4gjw/purchase.png">

**Comment by minhcasi** [comment]
@zemeister23 - please try to download the version that releases today to fix the issue -thanks

**Comment by zemeister23** [comment]
but how do I completely update the app

**Comment by zemeister23** [comment]
documentation or any things about updates?

**Comment by minhcasi** [comment]
@zemeister23 - please help to check the modified files list from the Gitlab repository, if you have customized the source, make sure all of these files are back up so that you can override to the release version

Link submit to access gitlab - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform
