### ISSUE TITLE
Fluxstore Update

### ISSUE THREAD

**Issue by arslan9999** [inspireui/support#2554]
I want to update my app, do I have to start everything over like configuration or Is there any other way to update APP right now I'm at Version 1.6.5

**Comment by minhcasi** [comment]
@arslan9999 - please help to check the modified files list from the Gitlab repository, if you have customized the source, make sure all of these files are back up so that you can override to the release version 

Link submit to access gitlab - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform
