### ISSUE TITLE
[Fluxstore] - 

### ISSUE THREAD

**Issue by ajaysinghof** [inspireui/support#2612]
Hey when i enable Cache in app it takes too much time to load main page approx 30 seconds to load . Please help me regarding this issue

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

**Comment by ajaysinghof** [comment]
![Screenshot_20200408-101435_Chrome](https://user-images.githubusercontent.com/63315789/78745431-cde06a00-7981-11ea-9dec-319a1b7ad432.jpg)

Here is the screenshot

**Comment by minhcasi** [comment]
@kvt0012 - pls help for investigating

@ajaysinghof - could you attache the common and config folder here - thank you!

**Comment by ajaysinghof** [comment]
[lib.zip](https://github.com/inspireui/support/files/4450602/lib.zip)

Hey common and config folder has been attached, 

Issue - When i enable isCaching it takes too much time to load app approx 30 seconds

**Comment by ajaysinghof** [comment]
Hey please help me tackle this problem

**Comment by kvt0012** [comment]
Dear sir, which simulator you use? 
Thank you

**Comment by ajaysinghof** [comment]
I'm running it on all the devices including Android 8 9 and 10, but still
getting the same error

**Comment by ajaysinghof** [comment]
Please help me regarding this issue its the major issue

**Comment by kvt0012** [comment]
Ah you mean that you build on Androi Studio and it takes more than 30 seconds ? 
Or you just run the app, sir

**Comment by ajaysinghof** [comment]
Yes i have edited the code in android studio and run it on my devices using
data cable then its take 30 seconds when i enable isCaching ,

**Comment by AbdallaSamy** [comment]
Yes same happens here, Home screen does not show unless the cache call returns response. So i had to disable the cache to make the home screen load faster.

**Comment by ajaysinghof** [comment]
But when caching is disabled then app is so slow to load content

**Comment by ajaysinghof** [comment]
Please help up out regarding this... Fluxstore

**Comment by ajaysinghof** [comment]
Why you all are not responding to us...

**Comment by minhcasi** [comment]
@ajaysinghof - @AbdallaSamy  there is 2 solution to apply the caches

1. Store the config_en.json to CDN and replace the local config.json by new CND URL from the config

2. Upload the config json file to mstore-api on the website, and enable isCaching: true - please check this guide - https://docs.inspireui.com/fluxstore/performance/#1-caching-to-improve-app-performance  - after enable the cache, you can test the URL to see if it is loaded fast - https://mstore.io/wp-json/mstore/v1/cache

Hope it clarifies your questions. Would you mind to share your caching URL here so that we could have a quick check?

**Comment by ajaysinghof** [comment]
Hey thanks for your response,  here is my caching URL https://frink.in/wp-json/mstore/v1/cache , it takes time when i enable caching in App,

**Comment by AbdallaSamy** [comment]
@ajaysinghof I am not sure if the app stores the products locally in case "isCaching" is enabled, because my app still takes time to reload all the products again even when isCaching is true. 
So What I can see in my app is that "isCaching" only fetches the config file from the server to make it dynamic so that you can change home layout on the fly.
Let me know if isCaching stores the products locally, if this is the case I can find a workaround to keep the app store the data **but not** fetch the JSON each time after splash screen(in case you can live without having the option to change the home layout dynamically).

**Comment by ajaysinghof** [comment]
Hey Fluxstore member, please help us out with this problem. We are unable to  get a good response

**Comment by kvt0012** [comment]
Dear sir, can you send your project via my email, I will check it for you, thank you.

**Comment by ajaysinghof** [comment]
Send me your E-mail ID please

**Comment by ajaysinghof** [comment]
Hey my project is very high in space its 1.3GB in size so i'm unable to
send it,

**Comment by minhcasi** [comment]
try to remove the `build` folder, `android/.grade` folder, `ios/.sysmlink`, `ios/Pods`
