### ISSUE TITLE
Fluxstore Pro - OneSignal notification to open certain activity in app

### ISSUE THREAD

**Issue by ranapiyush1986** [inspireui/support#2613]
1. My issue: hello acceding to https://github.com/flutter/flutter/issues/23549

 I need to open product category from notification click with one single I try below code but this is not work

fluxstore version is 1.6.3

OneSignal.shared

            .setNotificationOpenedHandler((OSNotificationOpenedResult result) {

        setState(() {

          Product.showList(context: context, cateId: 5, cateName: 'categroy name from result');

        });

          print(result.notification.jsonRepresentation().replaceAll("\\n", "\n"));

        });

2. Screenshots issues (required):

3. Proof of my purchased (required): attached
![75575075-777c3380-5a85-11ea-9d5e-824a671df4ea](https://user-images.githubusercontent.com/18486814/78710706-6c91aa00-7933-11ea-9f56-c6ec454cf863.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@ranapiyush1986 - please help to check the detail customize form onesginal user guide - https://documentation.onesignal.com/docs/flutter-sdk-setup

From version 1.6.5 - we have fixed onesignal could get the detailed push to notify message and saved to the history 

But Since version 1.6.6 - We are pending support this library due to the build issue from this library (as it is not quite stable and cause the build broken)

You can also submit to this link to asset the gitlab - https://docs.google.com/forms/d/e/1FAIpQLSeuBqUkScy42V7KKhfNPj0fl581anrB1mWkbMa3p2WQt7fhfw/viewform - thank you!
