### ISSUE TITLE
[ListApp] Need help in connecting my wordpress site with listapp

### ISSUE THREAD

**Issue by dhruva7782** [inspireui/support#264]
**Mandatory Info (please complete the following information):**
 - Product: [ListApp]
 - Your Purchased Code: [0a72ecc4-202a-4bfb-8528-ff0a87e54084]

**Describe the issues**
Please help me with installation and connecting my listify site to the listapp.
I am not a coder or developer. I have listify theme running on wordpress. the url is https://whatsder.com
I am working on a windows computer running windows 10 os. I tried ce builder installation, manual installation. I sometime get errors on simulator, i am not sure which config file to edit as I have 3 config files(listify, listable and mylisting) because whenever i edit listify config file the app shows different options like mylisting demo options. I purchased listapp thinking it would be a bit easy to install this app by connecting to the site. i don't see any videos or instructions to achieve this with my current installation. I am sure i am not qualified or good enough to work on this one. I request someone to help me once. I can provide my wordpress admin credentials and cpanel credentials if required. all i need is to get it running once. I've been trying this from a long time now. I am getting different sort of errors. Any help is highly appreciated.
Thanks in advance

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by reconshield** [comment]
just follow official documentation : https://inspireui.github.io/listapp/docs/quickstart
they provide complete documentation.dont skip any setting.

**Comment by dhruva7782** [comment]
hello,

thanks for the reply,

i tried the documentation, i don't know where i am doing wrong. i am getting expected results. if possible can you please make a video for only listify theme and listapp

thanks,
dhruva

**Comment by reconshield** [comment]
send screenshot. Inspireui admin will follow up your issue.

**Comment by dhruva7782** [comment]
i will start from the beginning again and get the screenshot and share, thanks

**Comment by reconshield** [comment]
ok..Good Luck!

**Comment by dhruva7782** [comment]
hello,

thank you for helping me here. i did exactly the same way it showed in the documentation. i have published the app also. here is the expo link - https://expo.io/@dhruva7691/whatsder-app
now, the issue that i am facing is the app crashes when i click on any listings in the app.

please help
thanks,
dhruva

**Comment by minhcasi** [comment]
Hi, just update that we received your ticket and the team will back to check on Monday (after the Tet holiday), sorry for the delay - thank you!

**Comment by thangvo9x** [comment]
Hi. Thanks for your purchase. Pleas send screenshots help me such as AppConfig.json to thang@inspireui.com
Thanks

**Comment by freetimeforcash** [comment]
I am having the same issues, and there are many people that are having the same issues. Your documentation does not help me because I have followed every step and still no success. You have to understand that people who purchase your product like me are not coders, that is in fact why we purchased your product because we cannot do this ourselves. I understand that you are human, and I'm sure that it takes alot to take care of as many customers as you have, but has just become frustrating I'm sure for everyone involve including yourself. I appreciate the work you have already done to create the product, but for the installation on the customer side for people like myself, something is just not working correctly. I have even purchased a new laptop because my old laptop is 32bit and not sufficient to handle the load. Please help ASAP PLEASE!

Thank you in advance. I would like to leave you a better review than the one that I have left, and I will,, but you have to earn that by helping us to get this working!
