### ISSUE TITLE
Product variation error

### ISSUE THREAD

**Issue by emerfabiano** [inspireui/support#2661]
I have 4 attributes of a product.
Total of 118 variations.
Prices are being brought in only a few items. The others bring the price of the last variation.

**Comment by minhcasi** [comment]
Hi, thank you for the feedback. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

Also, share us the screenshot of the issues and common / config folder so that we could checking
