### ISSUE TITLE
[my-product] - 

### ISSUE THREAD

**Issue by opooletech** [inspireui/support#2664]
My Issue is how am show my latest product on home page becuse wordpress didnot give me ID number for Product
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:

2. Screenshots issues (required):

3. Proof of my purchased (required):

3. Config files (required)

**Comment by minhcasi** [comment]
@opooletech - thank you for the feedback. 

1. Could you help to share the screenshot of the purchase screenshot from http://codecayon.net/downloads it's used to verify your proof of purchase? 
Sorry for any inconvenience, we will reopen the ticket when it is verified, thank you!

2. Also, share the screenshot of the issues so that we could know where the feature to give the suggest for the issue

Thank you!
