### ISSUE TITLE
[FluxStore-WooCommerce] - WebView is not working & Images are not showing on Categories and Blog

### ISSUE THREAD

**Issue by saifmuhtar** [inspireui/support#2705]
> - Thank you for reaching please follow the format below to create a new ticket, please explain as more detail as possible and allow 24 - 48 hours to receive an answer to your ticket.
> - Try to explain your all problems in one ticket, instead of creating multi tickets.
> - After creating an issue, please take the screenshot of http://codecanyon.net/download - to let us know you have purchased our product, or quick note as a comment that you have created this ticket, example: https://tppr.me/DJA8L
> - IMPORTANT: We will close the ticket if you could not prove as our customer.

---------

1. My issue:
A) WebView is not working
B) Images are not showing on Categories
C) Images are not showing on Blog

2. Screenshots issues (required):
A) WebView is not working
![WhatsApp Image 2020-04-14 at 08 25 02 (2)](https://user-images.githubusercontent.com/34681804/79173244-8c403b00-7e29-11ea-97de-038eee8e006f.jpeg)
![WhatsApp Image 2020-04-14 at 08 25 02 (3)](https://user-images.githubusercontent.com/34681804/79173255-94987600-7e29-11ea-977f-6b8e49ac2c5a.jpeg)

B) Images are not showing on Categories
![WhatsApp Image 2020-04-14 at 08 25 02 (1)](https://user-images.githubusercontent.com/34681804/79173276-9f530b00-7e29-11ea-9c70-9049bd244201.jpeg)

C) Images are not showing on Blog
![WhatsApp Image 2020-04-14 at 08 25 02](https://user-images.githubusercontent.com/34681804/79173294-ab3ecd00-7e29-11ea-8aad-472607c2b288.jpeg)

3. Proof of my purchased (required):
![72332982-fc89d400-36f5-11ea-9307-f8c418404111](https://user-images.githubusercontent.com/34681804/79173322-c27dba80-7e29-11ea-8345-ef2685223cca.jpg)

4. Config files (required)
[config_en.json.zip](https://github.com/inspireui/support/files/4472488/config_en.json.zip)

**Comment by saifmuhtar** [comment]
I'm using the latest version, FluxStore WooCommerce 1.6.6b

**Comment by dttrung26** [comment]
Hi @saifmuhtar , please leave me your /lib/common folder for checking. 
Best!

**Comment by saifmuhtar** [comment]
[common.zip](https://github.com/inspireui/support/files/4472922/common.zip)

@dttrung26 I hope the best from you. Thank you.

**Comment by dttrung26** [comment]
Hi @saifmuhtar , 
a. All of your webview screens are still working fine mate. Please wait a bit 'cause sometimes it takes more time to load a webview than a widget. 


![2](https://user-images.githubusercontent.com/32586676/79199036-916bad00-7e5e-11ea-9c9d-1b62b591942e.PNG)
![1](https://user-images.githubusercontent.com/32586676/79199044-929cda00-7e5e-11ea-812d-9be66ee97dcc.PNG)

b. Category images are also working well mate. 
![3](https://user-images.githubusercontent.com/32586676/79199050-94669d80-7e5e-11ea-8246-0ad2b5df3056.PNG)

c. Your blog images are missing because in your site, images setup are not correct. 
![4](https://user-images.githubusercontent.com/32586676/79199112-ad6f4e80-7e5e-11ea-8af6-9f09bdadb8be.PNG)
Please make sure you followed our guide (https://docs.inspireui.com/fluxstore/woocommerce-setup/), especially for Regenerate Image plugin. 

Let me know if you are still in trouble. 
Have a nice day!

**Comment by saifmuhtar** [comment]
@dttrung26 Thank you for your great support. I will follow your guide.
