### ISSUE TITLE
[FluxStore-1.6.6 -Woo] - Payment UI of razorpay is different from previous  version of app. 

### ISSUE THREAD

**Issue by Lokeswara-betha** [inspireui/support#2709]
1. My issue:

In my previous version of app  I used to get a payment gateway web interface for razorpay like below image.

![image](https://user-images.githubusercontent.com/60268240/79195961-ce2ea880-7e4c-11ea-8928-4ffd04c198e3.png)

but in recent release of app , when ever I am doing payment with razorpay , It is navigation to app website. 

![image](https://user-images.githubusercontent.com/60268240/79196114-11891700-7e4d-11ea-8d86-68e883078427.png)

So , Is there any way I can use previous version payment page for razorpay. 

2. Screenshots issues (required):

3. Proof of my purchased (required):
![image](https://user-images.githubusercontent.com/60268240/79196267-6331a180-7e4d-11ea-81de-faaf129e37f9.png)

3. Config files (required)

**Comment by minhcasi** [comment]
@Lokeswara-betha - there is a critical issue from Razorpay that cause broken build on Flutter so that we remove this lib for a while, unstill if more stable we could support official this library again 

In the meantime please help to use this library by your own project setting - we still keep the code as comment file - make sure to include in on pubspec.yaml file - https://github.com/razorpay/razorpay-flutter

**Comment by Lokeswara-betha** [comment]
Sure, Thanks @minhcasi .
