### ISSUE TITLE
Fluxstore WooCommerce app 1.6b 5 april  : If product set as Backorder but in app it shows out of stock

### ISSUE THREAD

**Issue by vivekaris** [inspireui/support#2712]
1. Fluxstore WooCommerce app 1.6b 5 april  : If product set as **Backorder but in app it shows out of stock**

2. **SKU field  missing** ( in Product layout, in shopping Cart , wishlist .

3. **Blog layout unable to render images in blog** see the sample https://www.iotwebplanet.com/arduino-data-display-using-iic-i2c-lcd/     but in app its display its image tag . Kindly look in this issue.

4. **grid category layout not working** . its not showing any category.

5. onepage payment is false but still goes in webview( some mobile api level 21 )  goes to webview of website payment page.

 
kindly do above fixes as soon as possible. I am hurry to launch my app on playstore

**Comment by vivekaris** [comment]
SKU field missing solved .kindly work on other issue 

What about deep linking in app . I thought its not working now . if its working kindly share tutorial

**Comment by philipvu30** [comment]
Hi,

Please send your common folder including config.dart and config_en.json to this email: toan@inspireui.com. 
I need to reproduce your problems with your config.
Thanks

**Comment by vivekaris** [comment]
sure today i will send..

**Comment by philipvu30** [comment]
Hi,

1. It shows out of stock because we only check the product's stock quantity. This feature will be implemented later.
3. I tried many solutions but none is working right now. We are using this package: flutter_widget_from_html to convert your content into webview, but maybe there is a problem with it. So it will take a while.
4. Kindly list all your category ids and prefer images in this path lib/common/constants/images.dart: 
![image](https://user-images.githubusercontent.com/54442328/80372688-1b376380-88be-11ea-8c8d-2e2f22a8a88b.png)
5. Please set both of these to false
![image](https://user-images.githubusercontent.com/54442328/80373613-846ba680-88bf-11ea-8564-f625a6cd1b23.png)
6. What is wrong with the shipping method? Would you mind giving me more detail with images included? Thanks a lot.

**Comment by philipvu30** [comment]
Closed as no response from user. Kindly re-open issue if you need help.

**Comment by vivekaris** [comment]
> Closed as no response from user. Kindly re-open issue if you need help.

wrong shipping is major issue

**Comment by vivekaris** [comment]
check email : toan@inspireui.com 

all info already sent
