### ISSUE TITLE
[Fluxnews] Comment & Push Notification not working 

### ISSUE THREAD

**Issue by bidfor** [inspireui/support#2735]
1) Comment Feature not working.
After I comment it said "Comment succesfully" but the comment section is still empty. 

2) Push Notification not showing in Android emulator.
I have already setup one signal and able to detect the user.  I don't receive anything when I send notification with One Signal .

Proof of purchase 
![image](https://user-images.githubusercontent.com/2523772/79418821-1c2be380-7fe8-11ea-9be1-7f545d53bf33.png)

Common.zip
[common.zip](https://github.com/inspireui/support/files/4485098/common.zip)

**Comment by dttrung26** [comment]
Hi @bidfor ,
1. 
First, make sure your configuration is correct.
![image](https://user-images.githubusercontent.com/32586676/79434464-9fedcc00-7ff8-11ea-9cb7-11f5cd2ddf9a.png)

Then if it is, keep in mind that your comments need to be approved in Wordpress admin page in order to be displayed in your mobile app.
2.  
First, please make sure your Wordpress settings on Onesignal is correct (https://documentation.onesignal.com/docs/wordpress) 
Seconds, remember to update your `kOneSignalKey` at /lib/common/config.dart
Last but not least, keep this one checked when you edit/post a new blog. 
![image](https://user-images.githubusercontent.com/32586676/79436532-34592e00-7ffb-11ea-90cc-d29618b11d85.png)

Hope this helps.
