### ISSUE TITLE
Issue Needs Help

### ISSUE THREAD

**Issue by maximuskay2** [inspireui/support#2747]
Step 1 (require):

1.. I will love to remove other social login Except SMS and Signup
2. APP redirect to inline browser and shows Wordpress homepage After successful checkout
3. If i change SplashScreen App never pass Splash Screen

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com
<img width="1437" alt="Screen Shot 2020-04-06 at 2 43 59 AM" src="https://user-images.githubusercontent.com/4710692/79495752-1687cb00-7ff3-11ea-9d42-e23f364604e3.png">

*Note: please submit ticket support by following above 2 require steps, we may close the ticket without providing full information.*

**Comment by minhcasi** [comment]
@maximuskay2 
1. please try to customize this file https://tppr.me/9mHW0 - we suggest using this powerful tool so that you could customize any UI from the app https://docs.inspireui.com/fluxstore/customization/#1-how-to-customize-any-ui-from-app

2.3 - please provide more detail screenshot issues and config file so that we could reproduce and fixing
