### ISSUE TITLE
Login Google , SMS and Facebook

### ISSUE THREAD

**Issue by suhendranst** [inspireui/support#2895]
I am trying to configure Google, SMS and Facebook login

I tried it and it never worked

I show my configuration screenshot 
1. https://prnt.sc/s6mq4t 
2. https://prnt.sc/s6mr14 
3. https://prnt.sc/s6mrhi 
4. https://prnt.sc/s6mruq 
5. Login to Google https://prnt.sc/s6mtpu 
6. Login SMS https://prnt.sc/s6mueb

**Comment by mansoor88** [comment]
The screenshots link I am unable to see. Can you upload here so the problem solver can see it.

**Comment by minhcasi** [comment]
@suhendranst - pls help to check this setting - https://docs.inspireui.com/fluxstore/common-issues/ - there is the solution to fix SHA-1 issues 

There is also the document from Sign In section - https://tppr.me/z6wGg

Let us know your checking - thank you!

**Comment by suhendranst** [comment]
@minhcasi - I made SHA-1 through Android Studio and implemented it in Firebase

I followed the documentation well

But there is no change

**Comment by suhendranst** [comment]
I have successfully logged in using this trial number https://prnt.sc/s774hi

But I was not able to use another telephone number https://prnt.sc/s775sx

I have seen the documentation many times and tried it, but the same error still occurs

**Comment by minhcasi** [comment]
@trunghieuvn - pls help for a suggestion

**Comment by trunghieuvn** [comment]
> I am trying to configure Google, SMS and Facebook login
> 
> I tried it and it never worked
> 
> I show my configuration screenshot
> 
> 1. https://prnt.sc/s6mq4t
> 2. https://prnt.sc/s6mr14
> 3. https://prnt.sc/s6mrhi
> 4. https://prnt.sc/s6mruq
> 5. Login to Google https://prnt.sc/s6mtpu
> 6. Login SMS https://prnt.sc/s6mueb

Maybe you are missing some setup step. 
Please wait for me, I'm making videos and documentation step by step setup login Google, Facebook, Apple and SMS. I will send you as soon as done. 
Thanks

**Comment by suhendranst** [comment]
ok i wait for the video tutorial

other problem
I can't change the launcher icon https://prnt.sc/s7z6ja
I have replaced this icon according to the resolution https://prnt.sc/s7z8wz
and in the favicon section I have also changed all the icons https://prnt.sc/s7z9pz

Help me with this problem

**Comment by Alnaggar94** [comment]
@trunghieuvn @minhcasi  I have also the same issue I have followed all the documentation and set up the google-services.json and put the api keys and the Autofill address is working but SMS and google login not working I even tried it in the production APK on real phone also same  I have also updated the Hash file from google play 

https://docs.inspireui.com/static/a124e8f1e62d01c8bbdda8ca67ddf74d/9adbb/google_signin_OAuthConsentScreen.png
https://docs.inspireui.com/static/8993eb492b9395725d86f93ce0aa621c/bf511/google_signin_AuthorizedDomain.png
https://docs.inspireui.com/static/4e49150d25dbd23f678d49bca7f0f20e/d25cb/sha_firebase.png

I did everything, it was working fine in the previous version

**Comment by Alnaggar94** [comment]
@minhcasi @trunghieuvn - A lot of people are reporting the same issue, we have tried all the suggested solutions but not working it was working in the previous version, will it be solved soon it's been 5 days !!!

**Comment by trunghieuvn** [comment]
You please add me to source code and add to console firebase
hieu.trantrung1204@gmail.com

**Comment by Alnaggar94** [comment]
@trunghieuvn - I have added you to the firebase console and send the full source code to your email

**Comment by suhendranst** [comment]
@trunghieuvn - I have added you to the firebase console and send the full source code to your email

**Comment by Alnaggar94** [comment]
@minhcasi @trunghieuvn @suhendranst -

I have found the solution and I want to share for the people having the same issue or maybe you can add it the documentation, It was the SHA-1  from "Upload certificate" section you have to add both see the screenshots below explains :


#1
![c1](https://user-images.githubusercontent.com/49800146/80847354-fd4c6480-8c17-11ea-9d2f-a7eb8763f06f.JPG)

 
#2
![c2](https://user-images.githubusercontent.com/49800146/80847361-02a9af00-8c18-11ea-887c-d6c4ac43c522.JPG)


#3 
![c3](https://user-images.githubusercontent.com/49800146/80847373-105f3480-8c18-11ea-8671-cea25b07b524.JPG)

**Comment by minhcasi** [comment]
@Alnaggar94 - thank you,  it's explained on this link https://docs.inspireui.com/fluxstore/sign-in/#3-sms-sign-in but we will show it more clearly

**Comment by walidcpu** [comment]
@Alnaggar94 can you help me to fix it

**Comment by trunghieuvn** [comment]
Hi @suhendranst ,
I added SHA certificate fingerprints  (with fluxstore's default keystore) to your project. Results after adding:

![2020-05-02-18 28 24](https://user-images.githubusercontent.com/19247680/80862941-03d3ee00-8ca3-11ea-9160-f8c736dcd1c8.gif)


You see the instructions here and try to follow:

https://paper.dropbox.com/doc/Fix-Login-GoogleSMS--AzJqodsGy2_ZYR4hluGH2UTLAg-jy7aa8GBDhBliErF345M3

**Comment by suhendranst** [comment]
error still occurs in me

![Screenshot_18](https://user-images.githubusercontent.com/37798795/80865284-74ced200-8cb2-11ea-95ad-41b7da35e581.png)

**Comment by trunghieuvn** [comment]
please follow document and try add SHA1 key to console firebase 
https://paper.dropbox.com/doc/Fix-Login-GoogleSMS--AzJqodsGy2_ZYR4hluGH2UTLAg-jy7aa8GBDhBliErF345M3

**Comment by lpzczar** [comment]
I have a solution for the SHA1 certificates, the problem in my case was that I was not putting the SHA1 certificates of the keystore that was generated by me, but I was putting the ones that were by default of my computer

**Comment by harisms** [comment]
i'm facing the problem after following this link 
https://paper.dropbox.com/doc/Fix-Login-GoogleSMS-jy7aa8GBDhBliErF345M3

But the problem is when I run the command 
**keytool -exportcert -list -v -alias mstoreapp -keystore android/app/mstore.keystore**
it returns this error **keytool error: java.lang.Exception: Only one command is allowed: both -exportcert and -list were specified.**

I tried this command inside android/app folder 
**keytool -list -v -alias key -keystore mstore.keystore**
then it asks for a password I entered 123456 as per key.properties file. 
but it returned as password was incorrect. i tried the keydebug password 123456mstore. but it still shows password was incorrect. so I think the password was incorrect. 
_keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect
java.io.IOException: Keystore was tampered with, or password was incorrect
        at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:794)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:220)
        at java.base/java.security.KeyStore.load(KeyStore.java:1472)
        at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1086)
        at java.base/sun.security.tools.keytool.Main.run(Main.java:417)
        at java.base/sun.security.tools.keytool.Main.main(Main.java:410)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
        at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:792)
        ... 5 more_

**Comment by minhcasi** [comment]
@suhendranst @harisms - please help to check these video guide as well 

- Login with GG: https://drive.google.com/drive/folders/1-IWAUFkU34NFPQ5hDwY_VJCIvZ7lagv1?usp=sharing
- Login with Facebook: https://drive.google.com/drive/folders/176_H6kpToYpmAsgt7ZeQgRvsmwPxhktG?usp=sharing

**Comment by trunghieuvn** [comment]
> I tried this command inside android/app folder
> 
> **keytool -list -v -alias key -keystore mstore.keystore**
> 
> then it asks for a password I entered 123456 as per key.properties file.
> but it returned as password was incorrect. i tried the keydebug password 123456mstore. but it still shows password was incorrect. so I think the password was incorrect.
> 

Hi @harisms ,
Because the project is separate between the develop and release fields, if you are not clear about the problem, you will be mistaken.

When you build the debug, the application will retrieve keystore information at `android/key-debug.properties` . You can get the SHA1 code from the keystore file in folder `android/app`. In the case of using FluxStore's default keystore, the specific keystore path is

```
android/app/mstore.keystore
```

When you build release, the keystore information will be stored in folder `android/key.properties`. In the case of a build release, please call the build bundle script for the application to obtain the correct keystore.
command build release android:

```
 sh tools / build-appbundle.sh
```

In this case, the keystore file will be saved in folder `certs/` of the project. If you build release, please get the SHA1 code of the keystore file at the link (default of FluxStore)

```
certs/key.jks
```
