### ISSUE TITLE
[Fluxstore] Error and Features

### ISSUE THREAD

**Issue by Saifahmad99** [inspireui/support#2955]
Step 1 (require): detail issues and screenshots
I Have Four Issues all are below along with screenshots

1. Can I change the menu button which is in the top left corner?
![WhatsApp Image 2020-04-30 at 8 47 47 PM](https://user-images.githubusercontent.com/59877416/80728083-28558c00-8b24-11ea-81bd-62a8b30302ca.jpeg)

2. Can I create categories on my app like this which is on my website on the home page you may visit https://www.celkart.com
![WhatsApp Image 2020-04-30 at 8 47 47 PM (1)](https://user-images.githubusercontent.com/59877416/80728213-4d49ff00-8b24-11ea-9dee-6a906ae0ebdc.jpeg)

3. Having Error on Facebook login
![WhatsApp Image 2020-04-30 at 8 47 47 PM (2)](https://user-images.githubusercontent.com/59877416/80728546-ad40a580-8b24-11ea-8c50-aa1b2122081e.jpeg)

4. Recently I'm using Fluxstore 1.6.3 How do I upgrade it without changing the whole code?

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
1,2 - could you config via fluxbuilder http://fluxbuilder.com/ then expo the json config to your app

3. open the Facebook setting and update the hashkey to match with your Android key - https://stackoverflow.com/questions/43956008/facebook-login-android-this-app-has-no-key-hashes-configured - also share the SHA1 on this guide https://docs.inspireui.com/fluxstore/sign-in/

4. You could refer to our Gitlab to get a list of file change, the project structure could change a log since 1.7.0

Let us know if you have any questions - thank you!

**Comment by Saifahmad99** [comment]
Cant Use Photo From Folder Using Fluxbuilder
