### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by lpzczar** [inspireui/support#2956]
Firebase Auth Error
In my Flutter app i have an issue about flutter. When i change the package name and the GoogleServices.json the firebase auths fail, and appears the next issues

Facebook Login:
image1.jpeg

Google Login:
image2.jpeg

SMS Login
image3.jpeg

Also, when i sign with the email the circular progress bar loads indefinitely
image4.jpeg

![image2](https://user-images.githubusercontent.com/19940455/80734675-22848a00-8ad5-11ea-80a6-7fc5c07c4cca.jpeg)
![image3](https://user-images.githubusercontent.com/19940455/80734681-24e6e400-8ad5-11ea-852a-836e07aef007.jpeg)
![image1](https://user-images.githubusercontent.com/19940455/80734687-26181100-8ad5-11ea-8f78-8c4860dc96fa.jpeg)
![image4](https://user-images.githubusercontent.com/19940455/80734691-27493e00-8ad5-11ea-92d8-b3bc655cb391.jpeg)

**Comment by hengsoheak** [comment]
me too

**Comment by minhcasi** [comment]
@lpzczar @hengsoheak could you double-check this guide - https://docs.inspireui.com/fluxstore/sign-in/#1-google-sign-in

**Comment by immortal-kid** [comment]
Even i'm facing this issue, i did everything as per documentation

**Comment by lpzczar** [comment]
I followed it step by step and it follows the same error.

Is there a solution for this?  or I will need my refund.

**Comment by minhcasi** [comment]
@lpzczar - try to read the guide carefully, you could search SHA-1

**Comment by lpzczar** [comment]
I have done it and the result is the same.

**Comment by minhcasi** [comment]
@lpzczar - pls try this note - https://paper.dropbox.com/doc/Fix-Login-GoogleSMS--AzJqodsGy2_ZYR4hluGH2UTLAg-jy7aa8GBDhBliErF345M3 - we will add new video soon - thank you!

**Comment by lpzczar** [comment]
I have followed the steps and everything remains the same.  They really aren't giving me a solution.  It is a good product but I feel annoyed because it is not working.

**Comment by trunghieuvn** [comment]
Please check to help me with the following:

1. Make sure the keystore when building correctly with the keystore you have added SHA1 to firebase.

Because the project is separate between the develop and release fields, if you are not clear about the problem, you will be mistaken.

When you build the debug, the application will retrieve keystore information at `android/key-debug.properties`. You can get the SHA1 code from the keystore file in folder `android/app`. In the case of using FluxStore's default keystore, the specific keystore path is

``.
android/app/mstore.keystore
``

When you build release, the keystore information will be stored in the `android/key.properties` folder. In the case of a build release, please call the build bundle script for the application to obtain the correct keystore.
command build release android:

``
 sh tools / build-appbundle.sh
``

In this case, the keystore file will be saved in folder `certs/` of the project. If you build release, please get the SHA1 code of the keystore file at the link

```
certs/key.jks
```

2. After making sure you have taken the right keystore for each use case, please check to help me, did you follow the steps to create the Oauth Consent Screen? This step is very important, if not performed correctly this step will cause errors for Google login and SMS.
Video tutorial: https://drive.google.com/file/d/1OEsu8L5pyc7mXji0bsQfFXG-zmB0XHqm/view?usp=sharing

3. If you did it correctly (1) and (2) and still get an error, please add me to your github / gitlab and firebase project, I will check and find out the specific cause, then will guide you how to fix it.

github/gitlab/mail/firebase: hieu.trantrung1204@gmail.com
