### ISSUE TITLE
[Fluxstore Pro] after update affiliate links doesn't WORKKKKKKKK

### ISSUE THREAD

**Issue by san2pedro** [inspireui/support#2982]
![Screenshot_1](https://user-images.githubusercontent.com/13208693/80866819-8788dd00-8c99-11ea-8dd6-c4526029aa90.png)

after update affiliate links doesn't work!!!!
press on buy now button nothing heppend!!!!!
![f74eec93-e4ba-4b92-bef4-a192b1079ae3](https://user-images.githubusercontent.com/13208693/80866870-c880f180-8c99-11ea-9aa6-32417f3a462c.jpg)

**Comment by maynard88** [comment]
have you verified your license on mstore plugin?

**Comment by san2pedro** [comment]
nope let me try

**Comment by san2pedro** [comment]
nope dosnt work.
press buy now nothing heppend
![Screenshot_2](https://user-images.githubusercontent.com/13208693/80868563-29adc280-8ca4-11ea-9e0c-d3d7e5190f5e.png)

**Comment by maynard88** [comment]
Sorry am just one of the clients as well. Did you tried to click the buy button on the website version of your store? Because buy button works on the website version then it should work on the app as well unless you have custom hooks(actions/filters) added to the buy button of woocomerce. 

Quick question, are you using the updated version 1.71 of fluxstore?

**Comment by san2pedro** [comment]
maynard88 big thank you all work was problem with plugin lol forget turn off!

**Comment by maynard88** [comment]
Happy it all works out. Just for reference in case somebody will encounter the same problem.

1. If it works on website version of woocomerce it should also work on mobile version unless the website version has custom hooks ( actions/filters) added to it). I assume the fluxstore api cannot render those hooks.
