### ISSUE TITLE
Select categories in the app

### ISSUE THREAD

**Issue by lpzczar** [inspireui/support#3059]
Hi, I hope you are well.

The app is amazing, but I would like to make some customizations. I want the categories section to only show some categories that I choose myself and not show all. And I want to know how many categories the app can show.

Thanks for your reply.

![abb2b213-b661-4265-8dfb-c3f42b285c61](https://user-images.githubusercontent.com/19940455/81242684-63980500-8fd3-11ea-9cc8-8f93707fa9ed.jpg)

**Comment by minhcasi** [comment]
@lpzczar - please help to follow our update on next release, we will add new CategogyFilter from the config json file - by this way you could able to control the Category Order from Fluxbuilder and display the list of category as your wish 

It's on our backlog, so that i will close this ticket - pls follow us on these link to get further update - http://medium.com/@inspireui or http://youtube.com/inspireui - thank you!
