### ISSUE TITLE
error in home in new update 

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/support#3082]
I update to new version 1.7.3
but when I finish I see this error 
<img width="1440" alt="Screen Shot 2020-05-08 at 1 15 04 AM" src="https://user-images.githubusercontent.com/35544603/81353664-f61ad000-90c9-11ea-912d-e51d60d047b1.png">
<img width="1440" alt="Screen Shot 2020-05-08 at 1 18 36 AM" src="https://user-images.githubusercontent.com/35544603/81353666-f74bfd00-90c9-11ea-9a36-e2b7e66fafae.png">

from where can I solve this

**Comment by abqrinou** [comment]
I have same  Issues

**Comment by siyashamsudeen** [comment]
have the same issue .

**Comment by minhcasi** [comment]
@mohamedibrahim89 - pls add this setting to fix the issue from the config json file, we will fix it on next release, this is caused by the sticky banner option - thank you!

<img width="881" alt="Screen Shot 2020-05-08 at 11 22 03" src="https://user-images.githubusercontent.com/1459805/81369970-25f3c300-911e-11ea-8efb-981faeec9047.png">
