### ISSUE TITLE
bug while filter items

### ISSUE THREAD

**Issue by stockracee** [inspireui/support#3122]
Step 1 (require): detail issues and screenshots
Bug:: I hv 600 prodoct(aprox) at my website, out of them 548 is under jewellery category. Now when I use filter to show only 548 product then app show only 22products, so many times i tried but result is same. Pl help also pl find bug video as https://envl.app/shareddrive2000/aQPFxL!qE6JroqdgYCoNFWL
https://filebin.net/cr8cpobcdxofxrl4/Recorder_20200509104925.mp4?t=0w5hu0xt

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Note: please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. Thank you 😊*

**Comment by minhcasi** [comment]
@trunghieuvn - pls update the code to resolve this issue - thanks

**Comment by stockracee** [comment]
> @trunghieuvn - pls update the code to resolve this issue - thanks

I already use updated version.

**Comment by stockracee** [comment]
I already use updated version

**Comment by minhcasi** [comment]
@trunghieuvn - could you give some update - thank you!

**Comment by stockracee** [comment]
I already use updated code 1.7.3. Also I already mention on comment & 
reply at github

On 10-05-2020 07:54:18, "Minh Pham" <notifications@github.com> wrote:


@trunghieuvn <https://github.com/trunghieuvn> - pls update the code to 
resolve this issue - thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/inspireui/support/issues/3122#issuecomment-626262704>, 
or unsubscribe

**Comment by trunghieuvn** [comment]
Hi @stockracee 

The cause is due to 2 problems:
- The first is the product price limit when you filter lower than the price of your products (I see a lot of prices> $ 500, while you filter with prices from $ 0 - $ 500). You can increase the maxPrice value to suit your product.

![image](https://user-images.githubusercontent.com/19247680/82071288-18cb6b00-9700-11ea-9117-a558c0fd74af.png)


- The second problem is that the SingleChildScrollView cannot contain a very long list. You should change to listView to be able to load your product list.

![image](https://user-images.githubusercontent.com/19247680/82071353-326cb280-9700-11ea-9ddb-6da29869ceee.png)
