### ISSUE TITLE
[ListApp] Connect ListApp to Existing MyListing Website

### ISSUE THREAD

**Issue by ctaylor7216** [inspireui/support#319]
**Mandatory Info (please complete the following information):**
 - Product: ListApp
 - Your Purchased Code: c1a47f7a-2421-470f-860c-4f13e0271439
(we may not reply if you are not our customer)

**Describe the issues**
I am a Windows 10 user with CeBuilder. I can not connect my existing website. www.opsatl.com which is using ListApp.  I have followed the YouTube video and install instructions.  

**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Hi, could you provide detail issues screenshoot ?

Try to update your correct URL, instead of the forwarding account, that could cause the issue - https://onpeachtreestreet.com/

<blockquote><img src="/wp-content/uploads/fbrfg/favicon.ico" width="48" align="right"><div><strong><a href="https://onpeachtreestreet.com/">On Peachtree Street – If It's On Peachtree Street, It's OnPeachtreeStreet.com</a></strong></div></blockquote>
