### ISSUE TITLE
How can i onfigure my Config_es.json so that I can add simple text labels, only one image, and text below any swiper carrousel of images  

### ISSUE THREAD

**Issue by andrex16** [inspireui/support#3252]
Step 1 (require): detail issues and screenshots

Wehere can in find the documentation about al the personalization that i can made to my config_es.json like add simple text, and one simple image, and text below and carrousell of images, etc.
because its too limite in kind of information that i would like to use in my app

Step 2 (require): verify license and sharing config files via this google form - http://private.inspireui.com (please don't share the screenshot purchase here)

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Hi, the config_es.json format will be the same with config_en.json 

1. you could manually update by using this guide - https://docs.inspireui.com/fluxstore/home-layout/
2. or upload that config json to the Fluxbuilder so that you could manage from there - http://fluxbuilder.com/

Kindly move you all question to the same ticket #3251
