### ISSUE TITLE
[MStore] I couldn't console.log

### ISSUE THREAD

**Issue by bugToaster** [inspireui/support#326]
**Required Info (please complete the following information):**

* Product: MStore App
* Your Purchased Code: 0031538f-de1d-427d-9e46-a183d5a1f1c2

**Describe the bug**
I could not install reacttron, I am developing my application on  ubuntu os.
I am trying to debug-ui. I was putting console.log() but it does not show anything.

***Reacttron issue***
If i usereacttron:false it generate cors issues and can't get data.

**Comment by luyx2412** [comment]
Hi @bugToaster If you debug with Reactotron which did not support debug UI. You can try https://github.com/jhen0409/react-native-debugger

Thanks

**Comment by bugToaster** [comment]
how to configure it? may you help?

**Comment by luyx2412** [comment]
Hi @bugToaster in Constants.js file, we have the field `useReactotron`, please change this field `useReactotron: false`. After that open your react-native-debugger application and open debug mode on simulator. https://facebook.github.io/react-native/docs/debugging

Thanks

**Comment by bugToaster** [comment]
![mstorecorsissues](https://user-images.githubusercontent.com/23161627/53462787-3f57a480-3a6f-11e9-99f0-51e39de0f564.png)

**Comment by luyx2412** [comment]
Hi @bugToaster What debugging tool are you using? react-native-debugger or default debug chrome.
- If you are using react-native-debugger, please make sure `useReactotrong: false` in `src/commons/Constants.js` file. And in `src/store/configureStore.js` file comment line from 46 to 52 look like the image.

![image](https://user-images.githubusercontent.com/8909619/53538869-f7558200-3b41-11e9-85de-49ab0fdb0eed.png)


Thanks

**Comment by bugToaster** [comment]
It did not generate error but still now there is no console.log()

**Comment by luyx2412** [comment]
Hi @bugToaster 
- If you are using Reactotron to debug, please use `import { log } from "@common"` --> `log("YOUR_LOG")`.
- And with react-native-debugger, you can use `console.log()` normal.

Thanks

**Comment by bugToaster** [comment]
`console.log()` is not working. As per your suggestion I did that but in my browser console I mean debugger-ui console is clear.

**Comment by luyx2412** [comment]
HI @bugToaster I did not meet the issue look like you, but you can read the article to fix. https://stackoverflow.com/questions/7124164/stop-the-console-log-clearing-when-you-click-a-link-in-google-chrome

Thanks

<blockquote><img src="https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon@2.png?v=73d79a89bded" width="48" align="right"><div>Stack Overflow</div><div><strong><a href="https://stackoverflow.com/questions/7124164/stop-the-console-log-clearing-when-you-click-a-link-in-google-chrome">Stop the console log clearing when you click a link in Google Chrome</a></strong></div><div>Referred to as the "JavaScript console", when you click on a link, the log is cleared.

Is there a way to stop this log from being cleared when you click on a link?

The problem is that an event </div></blockquote>
