### ISSUE TITLE
razorpay error

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3329]
no route was found matching the url and request method
Can you please help?

![image](https://user-images.githubusercontent.com/44862509/82495073-3da25280-9af3-11ea-9aec-bcf8d8cdb1e4.png)

**Comment by kvt0012** [comment]
Can you take a shot and describe more ? Thank you

**Comment by mmasifashraf** [comment]
@kvt0012  Please see the error screenshot 

![image](https://user-images.githubusercontent.com/44862509/82545313-357ffc80-9b5f-11ea-8009-cde625487da5.png)

**Comment by kvt0012** [comment]
> @kvt0012 Please see the error screenshot
> 
> ![image](https://user-images.githubusercontent.com/44862509/82545313-357ffc80-9b5f-11ea-8009-cde625487da5.png)

try to follow this guide, sir 
https://docs.inspireui.com/fluxstore/multi-payment/

**Comment by mmasifashraf** [comment]
@kvt0012  i have done all the steps mentioned in the docs.
I have noticed that payment_razorpay.dat named as  payment_razopay.dat in checkout screens , will it make any issue?
![image](https://user-images.githubusercontent.com/44862509/82556228-fd35e980-9b71-11ea-9e80-a70f8cb5e94b.png)

and is it mandatory to fill the callbackUrl value?

**Comment by minhcasi** [comment]
@mmasifashraf - sorry for the late response, this file used to support the Razorpay native library from this lib - https://github.com/razorpay/razorpay-flutter - due to this library is not yet stable and cause some build issue we are not supporting at this time, but we will create the Blog to clarify how to use it as native payment.

The current Razorpay on your site will be run as Webview, could i check if you have enable following config:
- Razopay on the website should be run correctly.
- The mstore-api is updated to the latest version and activate.

Thank you for your time!

**Comment by mmasifashraf** [comment]
@minhcasi 

State value is saving local successfully but not updating in wp order address details. 
is it working at your end?

![image](https://user-images.githubusercontent.com/44862509/82719256-87d13280-9cb1-11ea-97b8-f6f9d3a6616e.png)

**Comment by minhcasi** [comment]
@mmasifashraf we did not sync the state from the WooCommerce side as it is not content completely for all countries, that why we store is as local files from the mobile, you could config it from state_xx.json 

<img width="1121" alt="Screen Shot 2020-05-24 at 14 53 16" src="https://user-images.githubusercontent.com/1459805/82748696-4edab000-9dce-11ea-870a-ca471d8b5954.png">

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
