### ISSUE TITLE
Some Shipment Information

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3331]
I would like to add some more information as per below, could you please give me some examples.

- Free Shipment is Eligible/Not Elibile based on total value in Checkout Screen
- Pre-filled Country, State Values. 
- City and and Area List in address

**Comment by minhcasi** [comment]
@mmasifashraf 
+ You could use Inspector to navigate to the screen you need to customize - https://flutter.dev/docs/development/tools/devtools/inspector

+ we suggest to use `EnableOnePageCheckout: true` from the config file to enable the one page checkout feature if you would like to add more complex to the payment process, this feature will enable Webview at the first stage so that you don't need to implement new UI.

+ Please help us to post 1 ticket for your issues, we will keep this one #3329 open to continue further comments.
