### ISSUE TITLE
Error changing default language and currency with symbol and other errors

### ISSUE THREAD

**Issue by Marcleiton** [inspireui/support#3378]
Hello, I'm having trouble changing the default language, I've tried everything and it doesn't change, it is always necessary to go to profile> language after accessing the app to change, the default language is English, my language is another and it's already configured here on app.

1° The currency change is also not successful, I did as requested in woocommerce with WPML and without success too, could you help me? 

2° Currency, BRL, Symbol R$

3° I also have this image error fluxbuilder https://i.imgur.com/AftIizb.png

4° I would also like to remove it here, I didn't find it in the settings
https://i.imgur.com/HqGTKHE.png

5° I tried to add the "GuestCheckout": true, but it doesn't work, I put it in the informed place but it doesn't work and at all times the app closes https://docs.inspireui.com/fluxstore/config/

6° another point after confirming a purchase without payment via webview it does not update the application cart, any solution?

7° Alguns bugs no fluxbuilder após instalar o plugin WPML, e não é possivel alterar o idioma no fluxbuilder.
https://imgur.com/a/SQQZnFk

**Comment by Marcleiton** [comment]
I also have this image error https://imgur.com/a/FY4VoKT

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by Marcleiton** [comment]
Hello, send the requested data, another useful life, change the / id / project package to settings in firebase or use the ones that are informing the publication and make changes.

**Comment by dttrung26** [comment]
Hi @Marcleiton , 
- In order to change default language, please take a look at `kAdvanceConfig` var located at /lib/common/config/gereral.dart , and edit `DefaultLanguage` into your language code.  Remember that language code must be matched with those new config files (if you created) at /lib/config/config_[language_code].dart. 
1 +2. Changing currencies and symbols still work fine as I checked. Make sure that any changes you made (if any) do not affect source code mate. 
![image](https://user-images.githubusercontent.com/32586676/82858363-deeb3780-9f3d-11ea-8821-632b14e394ac.png)
![image](https://user-images.githubusercontent.com/32586676/82858374-e90d3600-9f3d-11ea-9cf9-11fa71c33379.png)
![image](https://user-images.githubusercontent.com/32586676/82858396-f4606180-9f3d-11ea-9922-e78d988d5c9d.png)
3 + 7. Please report this issue at https://github.com/inspireui/fluxbuilder/issues including more detail  (steps to encounter this issue, error log, attached detail image would be nice) 
4. This settings are not available in config. Please replace index.dart into /lib/widgets/frameworks/woocommerce/ in order to remove that part. 
5. Checkout without login still works fine as I checked. Along with what I said in number 1+2, please save your changes and do a "hot restart" to see your change reflect in your app. 
 
Let me know if you still have any questions. 
Have a nice day!

**Comment by Marcleiton** [comment]
If you need to change a currency to one that doesn't exist, it would be BRL (R$) for Brazil, not to be able to, from what I saw only through WPML in woocommerce but without success.  another doubt ru would like to know if i need to change the package / id to configure firebase or can i use what is informed in the application

**Comment by dttrung26** [comment]
Hi @Marcleiton , 
- In order to add new currency format, please configurate your admin site by following those guide: https://docs.inspireui.com/fluxstore/customization/#9-product-advance-options (Currency Switcher part), and add your new currency code by going to /lib/common/config/gereral.dart, in `const kAdvanceConfig` , add 
```
 {
      "symbol": "your-currency-symbol",
      "decimalDigits": 2,
      "symbolBeforeTheNumber": true,
      "currency": "your-currency-name"
    },
```
- In term of package name, I can say it depends. For example, Google Sign In requires a match in  package name in google-services.json with the one you registered in Firebase while other services might not. I highly recommend you follow our integration guide with the services that you want to integrate. When you encounter any problem with the package name, you would know how and when to fix it. 
- I forgot to attach index.dart file in your previous number 4 question, here it is. 
[support_ticket#3378.zip](https://github.com/inspireui/support/files/4686294/support_ticket.3378.zip)

Have a nice day!
