### ISSUE TITLE
FluxNews - Category Images

### ISSUE THREAD

**Issue by yullux** [inspireui/support#3397]
<img width="342" alt="Screenshot 2020-05-25 at 10 05 10 AM" src="https://user-images.githubusercontent.com/65419353/82799922-b9ddc280-9e72-11ea-8a56-73a799ed7af1.png">

How can I change these images?

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by yullux** [comment]
I have provided information - I just need to know where I can change the images for category section on FluxNews App - I don't need you to fix anything for me. You do not have this section documented which is why I am asking.

**Comment by yullux** [comment]
<img width="1425" alt="Screenshot 2020-05-25 at 12 51 59 PM" src="https://user-images.githubusercontent.com/65419353/82810482-8e64d300-9e86-11ea-8eb8-d27b41a166cf.png">
I have found it's location - but when I change the category ID + URL, it does not change on my app... How would you recommend me changing this?

**Comment by yullux** [comment]
I have managed to upload those photos - could you just check the line of code is ok and won't cause conflict. if this is correct way to do it.
<img width="1404" alt="Screenshot 2020-05-25 at 2 06 35 PM" src="https://user-images.githubusercontent.com/65419353/82817588-2669b900-9e95-11ea-9729-be1736a13c32.png">

**Comment by minhcasi** [comment]
@yullux - yes it is configured correctly. If you are using Unsplash image, please make sure to `crop` the image to a smaller size to get better performance loading from app https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=900&q=80

or it is better to download as the local `asset` file to load it after, rather than loading via URL

@dttrung26 - please help to upgrade our documentation for this section as it is important for most of the users at the first stage.

**Comment by dttrung26** [comment]
Category documentation is updated. Thanks for your helpful information @yullux  
Have a nice day!
