### ISSUE TITLE
How to show the service area in google map.?

### ISSUE THREAD

**Issue by mmasifashraf** [inspireui/support#3535]
I want to show the service area same as below image and alert the user if they are choosing any location out of that area. 
How it could be possible? Please share if you have any google map docs about these feature. 

![image](https://user-images.githubusercontent.com/44862509/83457217-ddec6580-a469-11ea-8f44-489508aaeb15.jpeg)

**Comment by minhcasi** [comment]
@mmasifashraf - i'm not sure if this document is related - https://developers.google.com/maps/documentation/javascript/examples/control-bounds-restriction

You could try to add the bound restriction from the app so that the user could not navigate outside the bound

Please help us to comment your all question/issues to the same ticket on #3516
