### ISSUE TITLE
Fluxbuilder "Image Cache Not Enabled" (When It Is)

### ISSUE THREAD

**Issue by eikliw** [inspireui/support#3555]
Fluxbuilder says the image cache is not enabled, when it is. 

I built my app with FluxNews before Fluxbuilder was available. But Wordpress install is the same. But now it says "Image Cache is not enabled". Regenerate Plugins is installed, has been since last build. All of Wordpress and plugins are updated.

Proof of purchase, please see ticket #2060

<img width="1193" alt="Screen Shot 2020-06-02 at 7 51 49 PM" src="https://user-images.githubusercontent.com/11740613/83580818-07110280-a50b-11ea-85e2-1486a97ac91e.png">

**Comment by minhcasi** [comment]
@dttrung26 - pls help investigate this issue

**Comment by mohamedibrahim89** [comment]
me2 and I make ticket but removed I don't know why

**Comment by dttrung26** [comment]
Hi @eikliw , 
May I ask did you install and enable "Better REST API Featured Images" plugin already?

**Comment by mohamedibrahim89** [comment]
u mean this plugin or another plugin 
https://wordpress.org/plugins/wp-rest-cache/
if u mean another plugin can u send link for

**Comment by dttrung26** [comment]
Hi @mohamedibrahim89 , 
The plugin I mentioned was  "Better REST API Featured Images" which you can find at this link: https://wordpress.org/plugins/better-rest-api-featured-images/
Please install and active this plugin for a temporary fix. The dependence on this plugin on checking cache image will be fixed in next patch FluxBuilder.
Nice day!

**Comment by eikliw** [comment]
@dttrung26 activating this plugin worked. Thank you!
