### ISSUE TITLE
FluxNews How do I cancel the welcome message

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#3629]
**How do I cancel the welcome message**

- FluxNews Version: 1.4.1
- Flutter : v1.17.1
- Testing Device/Simulator

![11](https://user-images.githubusercontent.com/54249914/83955737-0657d380-a85f-11ea-9524-793e2cec17fb.PNG)

**Other threads preview not working**
![111](https://user-images.githubusercontent.com/54249914/83955793-9ac23600-a85f-11ea-919c-95f0a12aee1b.PNG)

**Comment by dttrung26** [comment]
[support_ticket#3629.zip](https://github.com/inspireui/support/files/4749727/support_ticket.3629.zip)
Hi @haidarsalim ,
replace my file into your /lib/app_init.dart will disable OnBoardingScreen.
For the second issue, please specify a categoryId in your `VerticalLayout` config in order to enable `RelatedBlogList` layout. It looks like that: 

```
 "VerticalLayout":{
    "name":"Explore more",
    "layout":"list",
    "category": 42 
  },
```

Nice day!

**Comment by haidarsalim** [comment]
Thanks the problem was solved
