### ISSUE TITLE
FluxStore Listing App - Video is not showing on the detail page

### ISSUE THREAD

**Issue by paulagarciab** [inspireui/support#3650]
Hi There, 

On the listing detail page there is not code to show up the video of a product. 
on my config.dart I have showVideo = true, but if you check all the files for listing, there is nothing to display the video. 

Flutter 1.17.1
Listing App Directory Latest version you send me by email. 
Ticket ID for verification #3567

**Comment by philipvu30** [comment]
Hi,

It was removed in previous versions as inconsistent performance. If you have any idea where to put it in, don't mind sharing it with us. We will consider adding it in later versions. 

Thank you.

**Comment by paulagarciab** [comment]
Hi There,

Sorry but on the features that you offer on the website it says this:

Advanced product detail view. Display your products in the best way possible with multiple advanced configuration options including the option to show Safe Area, display videos and thumbnail galleries, add hero effects and change image heights.



________________________________

**Comment by philipvu30** [comment]
Hi,

Sorry that was our mistake. Currently, the app does not support showing the video feature.

If you have any idea about this feature, please share it and we'll add it in future releases. 
FYI, if you decide to embed the video to your app, it might not get the approval from AppStore and PlayStore due to their policy. 

Thank you.

**Comment by philipvu30** [comment]
Closed as no response in 2 days.
