### ISSUE TITLE
[FluxStore Woocommerce] Product page layout issues

### ISSUE THREAD

**Issue by and-eee** [inspireui/support#3662]
Hi guys, I'm not sure if this is something I did or whether it's the standard layout, but I have quite a large gap showing on the product list pages in all formats. I have 3 questions in relation to this:

1. How do I remove the big gap?
2. How do I change the default list mode?
3. How do I remove the two options in the top right ('list by' and layout options) so that users can only view in the default way?

I am attaching screen captures for your reference:

<img width="375" alt="Screen Shot 2020-06-10 at 3 41 02 pm" src="https://user-images.githubusercontent.com/63891246/84232513-c9782f00-ab33-11ea-9c83-5adeec7c015f.png">

<img width="375" alt="Screen Shot 2020-06-10 at 3 55 08 pm" src="https://user-images.githubusercontent.com/63891246/84232563-e1e84980-ab33-11ea-956e-39eaeef42bc7.png">

<img width="375" alt="Screen Shot 2020-06-10 at 3 55 54 pm" src="https://user-images.githubusercontent.com/63891246/84232572-e90f5780-ab33-11ea-8679-d71a7d1e488b.png">

<img width="354" alt="Screen Shot 2020-06-10 at 4 03 59 pm" src="https://user-images.githubusercontent.com/63891246/84232655-18be5f80-ab34-11ea-918d-8ead175d3b83.png">

Cheers.

**Comment by minhcasi** [comment]
we are checking and get back you soon

**Comment by and-eee** [comment]
SEPARATE ISSUE brought over from #3687 : I'm struggling to work out what "Screen" and "Tab" Banner Image types do. Are there instructions somewhere?

**Comment by and-eee** [comment]
**Separate issue 2:** Perhaps I'm not using this correctly but the **PostScreen** screen doesn't seem to be working for me (in FluxBuilder). Am I doing something wrong? Here is the example:

![image](https://user-images.githubusercontent.com/63891246/84472791-3b36b100-accb-11ea-99aa-16d4febb1544.png)

**Comment by minhcasi** [comment]
@dttrung26 - pls help to investigate this feature - thank you!

**Comment by dttrung26** [comment]
Hi @and-eee , 
did you fill in our [support request form](https://docs.google.com/forms/d/e/1FAIpQLScWOjkAJIWJ9rgb9alopfOqLsJrGKbFM5cCYj1JBfLKLsBblQ/viewform)? If not, please do so that I can investigate your config on FluxStore. 
Best!

**Comment by and-eee** [comment]
Code loaded. There are a number of other unrelated questions in this ticket that don't require code to answer. Re-listing these here for clarity:

SEPARATE ISSUE (1) brought over from #3687 : I'm struggling to work out what "Screen" and "Tab" Banner Image types do (ie what they're for and how they work). Are there instructions somewhere?

SEPARATE ISSUE (2): Perhaps I'm not using this correctly but the PostScreen screen doesn't seem to be working for me (in FluxBuilder). Am I doing something wrong? (See above for screen capture)

Thank you.

**Comment by and-eee** [comment]
SEPARATE ISSUE (3): https://docs.inspireui.com/fluxstore/firebase/  most images are missing and video doesn't match the written instructions, also video has no narration so it is difficult to uderstand what is being done. Unable to set up notifications. Can you please advise?

![image](https://user-images.githubusercontent.com/63891246/84734470-4435c400-afe4-11ea-880b-782baa7fc5cb.png)

![image](https://user-images.githubusercontent.com/63891246/84734522-72b39f00-afe4-11ea-98f4-d60e2c539deb.png)

**Comment by dttrung26** [comment]
Hi @and-eee , 
Let's solve your issues one by one. 
- For issue number 2, you can change the default filter product list by changing below value in config_[language-code].json
```
  "Setting": {
    "MainColor": "#CCA169",
    "ProductListLayout": "list", => Change this value into "list", "columns", "card", "horizontal" or "listTile" 
    "StickyHeader": true
  },
```
We realize the lack of this part in the document and will update this instruction in FluxStore docs soon. Stay tuned!
- For issue number 3, in order to remove those 2 action icons in the top right hand side, please download attached file and replace it into your `/lib/widgets/backdrop/ `
[support_ticket#3662.zip](https://github.com/inspireui/support/files/4785075/support_ticket.3662.zip)
- For issue number 1, can you tell me which product filter type you want to set as default? I'll send the temporary fix on this product type only. For long term solution, I'll update in FluxStore next patch. 

- For the last 2 separated questions, 
+ Initially, `Screen` banner image is used to navigate go a `PostScreen` widget, and a `Tab` banner image is navigated to another "tab" in `Tabbar`. However, I've just been announced about a bug in those 2 types. Please try avoid using those until next patch. Sorry for any inconvenience may cause. 
+ `PostScreen` is currently having a bug in supporting for FluxStore (as well as in FluxBuilder). We are working on fixing that and release the bug fixing on those 2 platforms in the next patch. 

Hope you are still doing fine with FluxStore as well as FluxBuilder and let me know if you still have any question.
Many thanks!

**Comment by and-eee** [comment]
Hey @dttrung26 , thank you for your clear and comprehensive response. 

**ISSUE 1**: I'd like to apply "columns" layout as the default if you could please resolve the space issue with that particular product type. While you do that, is it possible to allow product names to wrap to the next line? Many of our products have names that are truncated in the current single line name format (I may also still need to reduce font size because some are too long for 2 lines).

In relation to the various bugs with the `Screen` and `Tab` banner image types, do you have an approximate date for those to be resolved, as I can keep developing other aspects but need to let the team know when they ca star to test those features in the app. The main Home page is mostly finished apart from those external links. 

Have you guys discussed the possibility of giving multiple pages the same set of functions that exist in the 'Home' page? In other words, let users create multiple 'Home' pages which can inter-link? This could be used by people like me to create a page that includes - just as an example - an image header relating to a group of products, a blurb on that product subset and then a list of the actual products below. Or it could be used to display "hero' products in their very own section. This would give the resulting app an amazingly professional structure and realistically shouldn't require too much coding seeing as the Home page already works pretty well. 

I hope you'll take that into serious consideration! It would absolutely rock.

I'll await your answer on **possible timelines** for expecting the bugs to be worked out with the `screen` and `tab` functions and also for the **updated product widget** (columns style) with additional line wrapping and the large white spaces removed.

Thanks again, looking forward to kicking this into high-gear!

**Comment by and-eee** [comment]
### NEW ISSUE (4): 

We have products that change status a number of times a day, and I am finding that using these settings in **general.dart** causes the status on the product list to not be refreshed when necessary. A product can appear **in stock** in the **product list** but then be found to be **out of stock** in the **product page**. This can be resolved by setting `isCaching` to `false` but that effects performance substantially. Can the product status on the product list page be set to refresh outside of the cache?

![image](https://user-images.githubusercontent.com/63891246/84856360-d2c04900-b0a9-11ea-9585-f5715af49e7b.png)

**Comment by and-eee** [comment]
### NEW ISSUE (5):

Can **billing address** fields and **phone number** be entered by customers in the **native registration page**? We use Square for payment processing so we are using webview checkout. I'd like to make the checkout page as simple as possible by removing the need for address and mobile number there.

**Comment by dttrung26** [comment]
Hi @and-eee , 
- For issue#1:
    + Please download and replace below file into your /lib/widgets/product/. It should remove large white space and wrap 2 lines of product title as you requested. 
[issue3662.zip](https://github.com/inspireui/support/files/4790679/issue3662.zip)
   + To be honest, I cannot tell you the time when new patch released because there are many factors affecting it. If you don't mind, please check the update status on codecaynon frequently. I'm so sorry for not able to help you with this. 
   + The feature you've just requested sounds great, I have to say that. However, this belongs to the customization service. If you really in need of that feature, please contact our tech lead via minh@inspireui.com and declare your request. If our team are available, we could discuss this feature deeper later on :D

**Comment by dttrung26** [comment]
Hey @and-eee , it's me again 😄 

After discussing with my tech leader, I'm sorry to announce that those 2 features are not available at the moment. However, we will move your request #4 and #5 into backlog for reference. If more users wish to have that same features, we might execute those in the near future. As I said, if those features are really really important to your business, kindly contact Mr. Minh via minh@inspireui.com for customization services if possible. So far that's all I can help. 

Your app looks very stunning, btw 😉 
Best!

**Comment by and-eee** [comment]
Thanks @dttrung26 ,

I can see how **issue 5** would be a customisation but isn't **issue 4** just a bug with the way caching works? Aren't all users experiencing the same fault?

**Comment by dttrung26** [comment]
Hi @and-eee , 
Can you give me a demo when you encounter this issue, please? A short video would be greate!

**Comment by and-eee** [comment]
Hi @dttrung26 , here you go, you'll note that when caching is set to `true` the stock status doesn't update in the product list. When set to `false` it works correctly but it doesn't have the performance benefit that caching gives:

https://www.dropbox.com/s/bhzdynushwoaeq7/ScreenCapture.zip?dl=0

**Comment by dttrung26** [comment]
Hi @and-eee , 
sorry for the late response. The purpose of `isCaching` is to optimize user's performance by not reloading config again when experiencing the app. That's why when you set enable `isCaching`, product layout will not be loaded again. However, product detail screen always needs to be reloaded due to special data events. Therefore, please consider using this feature if your site is mostly "static". Otherwise, turn this one off if you need your data always up-to-date.
Once again, sorry for the late response from us. 
Let me know if you still have any question. 
Best!
