### ISSUE TITLE
Product offer price issue

### ISSUE THREAD

**Issue by basithzan** [inspireui/support#3693]
Product discount price is showing different in category page and product page. Pls help!!

![IMG_5552 2](https://user-images.githubusercontent.com/12207952/84426046-32e56400-ac40-11ea-9f7d-6709a4591443.jpg)
![IMG_5553 2](https://user-images.githubusercontent.com/12207952/84426063-3a0c7200-ac40-11ea-929b-88d43bb7952c.jpg)

**Comment by sketchuprzr** [comment]
I'm using the latest version of fluxstore. I couldn't see such a problem. please check your website and metadata. or if you made an edit, check the application's source files. because as I said I couldn't see such a problem.

![image](https://user-images.githubusercontent.com/60021696/84433542-1c86da80-ac37-11ea-9a8e-82d932102c91.png)

![image](https://user-images.githubusercontent.com/60021696/84433548-1f81cb00-ac37-11ea-99fd-6b26dff3ab38.png)

**Comment by basithzan** [comment]
> I'm using the latest version of fluxstore. I couldn't see such a problem. please check your website and metadata. or if you made an edit, check the application's source files. because as I said I couldn't see such a problem.
> 
> ![image](https://user-images.githubusercontent.com/60021696/84433542-1c86da80-ac37-11ea-9a8e-82d932102c91.png)
> 
> ![image](https://user-images.githubusercontent.com/60021696/84433548-1f81cb00-ac37-11ea-99fd-6b26dff3ab38.png)

Can you pls share me the screenshot of the product with different variations (color and size)?

**Comment by minhcasi** [comment]
@basithzan - could you confirm to test on the latest release `1.7.5`? Our demo app on appstore could be out-date compare with the latest source - thank you!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by basithzan** [comment]
This is the screenshot from 1.7.5 !!!

![Screenshot 2020-06-22 at 1 07 54 PM](https://user-images.githubusercontent.com/12207952/85261209-73877d80-b489-11ea-9b4b-b202ddb08027.png)

@minhcasi
