### ISSUE TITLE
FluxNews - Categories not showing from website

### ISSUE THREAD

**Issue by yullux** [inspireui/support#3713]
I have 64 categories and only 2 categories are showing... with another 2 subcategories.

My app is on app store, I have recently edited my categories on my website and they disappeared / stopped listing on my app.....

**Comment by yullux** [comment]
https://imgur.com/a/sioHObN

**Comment by yullux** [comment]
Can someone show me how to change from showing only '10' categories to more please - I believe this will fix the problem.

**Comment by minhcasi** [comment]
@yullux - thank you for reporting - we will investigate this issue and let you know in 1-2 days

**Comment by dttrung26** [comment]
Hi @yullux , 
please fill in our [support request form](http://verify.inspireui.com) including your config files so that I can run some tests on your config. 
Best!

**Comment by yullux** [comment]
You took fucking 4 days to reply that? You're a joke for a company. I already fixed by myself, i asked how to change categories, this is ridiculous and I shall be reviewing this app.

**Comment by dttrung26** [comment]
Hi @yullux , 

First of all, I'm sorry for taking so long to reply your ticket. 
Second, as noticed in our pin post which you can find here: https://github.com/inspireui/support/issues/2734. Every issue must be included with config folder so that we can run test on your integration website. 
In terms of your issue, I do not know for sure whether this limited categories issue comes from our own demo site, or only with your integrated website. That's why I'm asking for your form fill-in in order to save time for both of us. I do not have any meaning in delaying your ticket. 
Anyway, glad to know that you are able to fix that by yourself. 

Let us know if you still have any question. 
Thanks!
