### ISSUE TITLE
Integrate select a product quantity per pounds

### ISSUE THREAD

**Issue by gmediard** [inspireui/support#3739]
This is a continuation of a closed issue. #3553 

Hello, my apologies for not following the previous thread. Indeed the plugin they mention (https://woocommerce.com/products/measurement-price-calculator/).

It is the one that you install in Wordpress, to integrate the function of selecting a product by weight.

I don't know how to send the configuration to them. The Plugin itself adds some fields to select the measurements (weight, length, altitude, volume) according to the rules (kilo or ounces, volume, liters, etc.) in the woocommerce config.

And then on the product it allows you to select to what extent the price of the product will be based, and it allows you to select a checkbox so that the customer can enter a personalized quantity (5 ounces, 15 ounces, 17.4 ounces, etc.).

**Comment by minhcasi** [comment]
@gmediard - as this feature base on extra integrate with the plugin `measurement-price-calculator` which is not supported by default WooCommerce API so that it could not run from the app.

Kindly add your customization to support this feature, pls move your all ticket comment to the same ticket #3741
