### ISSUE TITLE
Issue with MStore API Key

### ISSUE THREAD

**Issue by RohithKilaparthi** [inspireui/support#3925]
I had to reinstall the wordpress on my server and now, when I am trying to add the key to Mstore API, it says:
<img width="888" alt="Screenshot 2020-06-26 at 6 32 57 PM" src="https://user-images.githubusercontent.com/13035828/85860107-dd7e8a80-b7db-11ea-91f4-8f43e256c507.png">
Please let me know what needs to be done to fix it.

**Comment by ameenbadri7** [comment]
if you have changed the domain name our team will set up a new one for you. 
because your verification code if connected to the old name.

Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
verified ✅

@RohithKilaparthi - pls help us to update the Mstore-api to latest version to fix this issue - thank you!

**Comment by rc2HkBr** [comment]
I change the domain of my project and now my 
Item Purchase Code: stay whit my old domain mail, how to fix this problem?

**Comment by minhtruong315** [comment]
Hi @rc2HkBr You can send the request to change domain to email: support@inspireui.com
Thanks
