### ISSUE TITLE
Google Signin problem ( FluxStore Listing )

### ISSUE THREAD

**Issue by ton2engin** [inspireui/support#3958]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

Hello sir,
I have problem google singin with refer picture 
- SHA-1 already.
- Firebase already 
- Google-services.json already
 firebase_database: ^3.1.6
  google_sign_in: ^4.5.1

*** Facebook login working 

<img width="318" alt="Screen Shot 2563-06-28 at 16 50 11" src="https://user-images.githubusercontent.com/65043311/85944619-57d91700-b962-11ea-8da2-22f9dff191b0.png">

Please support ,Thank you.

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
@ton2engin Wellcome back.
I assume that you downloaded the latest version and you double-check those [guide](https://docs.inspireui.com/fluxstore/sign-in/#2-google-sign-in) and [this also this guide](https://docs.inspireui.com/fluxstore/sign-in/#2-google-sign-in)

so I guess you should also double-check this : 
Open file `project.pbxproj` in your project flutter at ` ios/Runner.xcodeproj/project.pbxproj` , search with keyword `PRODUCT_BUNDLE_IDENTIFIER ` to get Bundle ID you can get the basics from the [link](https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8)
and also you should add you SHA-256
![sha_firebase](https://user-images.githubusercontent.com/37524186/85953381-882bb000-b978-11ea-811b-c8886b4d6ce8.png)

could you double-check everything because today I started a new project and google SMS and Facebook all thing is ok.

**Comment by minhcasi** [comment]
@ton2engin - try to check solution on #3151

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
