### ISSUE TITLE
Home Page UI Issue

### ISSUE THREAD

**Issue by grnas00** [inspireui/support#3960]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: i faced an issue when home page scroll the product in left and right have transparent background  i need when scroll the header background hide please look screenshot
+ Product & version: Fluxstore MV 1.7.5
+ Flutter (or React Native) version:  Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.900])
+ Testing Device/Simulator:  Simulator Android SDK 29.0.0

+ Screenshot issues (drag the file to attach here): 

![Screenshot_1593360558](https://user-images.githubusercontent.com/24503019/85952776-3d0f9e00-b974-11ea-938e-d7cc14e63960.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

I cloud not find that you have filled this or not please resend submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

I'm sorry to close this ticket as there is no response or active conversation, 
please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by grnas00** [comment]
hello Ammen i fill form after post issue

**Comment by ameenbadri7** [comment]
Dont worry our team will investigate about your problem and it will be solved as soon as possible.
Allow is from 2 to 24 hours . we will reply.

**Comment by philipvu30** [comment]
Hi,

I'm sorry but this is not a bug. If you want that kind of design, you can start with this file lib/screens/home/home.dart to modify it using Sliver.
You can refer to this [video](https://www.youtube.com/watch?v=E3-WdYBrEDc) to know how to implement it. 

Thank you.
