### ISSUE TITLE
Images Size issues + Fb login issues

### ISSUE THREAD

**Issue by TqwaAlTurki** [inspireui/support#4000]
Hello, i'm using Fluxstore WooCommerce version 1.7.4 and i did run it on multiple android emulators and found those issues.
Looking for help asap as i'm releasing the app soon. Thanks a lot for your efforts. 
Issue No1: Product image thumbnails size are not compatible! 
Issue No2: Some products shows the price 0.00, how to fix that?  
Screen shot of issue No1+ No2: shorturl.at/opE78
Issue No3: Fb login won't work correctly even though i followed all the instructions!

**Comment by minhcasi** [comment]
@TqwaAlTurki - would you mind to merge the latest fluxstore 1.7.5 that fix some major issues related to your reporting ticket. You could try to use the Gitlab to merge your existing code, please follow this guide - https://medium.com/@inspireui/how-to-upgrade-fluxstore-projects-by-using-git-cebde7489ea6 - thank you!

**Comment by TqwaAlTurki** [comment]
@minhcasi Hi Minh, i tried the version 1.7.5 few weeks ago and it was very slow, the app crashes after five minutes that's why i rolled back to 1.7.4 as i experienced it's stability. 
however can you help me in fb login issue?

**Comment by minhcasi** [comment]
Hi @TqwaAlTurki - we could reproduce the crashing issue on fluxstore 1.7.5, pls give more detail so that we could have a check. 

Please also try to update the latest mstore-api to fix the login issue - we also write the detailed facebook login guideline here - https://medium.com/@inspireui/setup-facebook-login-for-flutter-apps-4e7bd031479d thank you!
