### ISSUE TITLE
Not able to signup or login

### ISSUE THREAD

**Issue by rushank** [inspireui/support#4084]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues:  
**Signup :** 
1) When i do signup with first name , last name , email & password. It insert data on woocoomerce database and also return the token but it keeps showing loading.. on button. It is not redirect to after successful signup
2) Same happened with signup with google. 

**Login :**
1) After enter correct email and password it shows loading also got token from API. It is not redirect to main screen. It just keep showing loading..
+ Product & version:  https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325
Version - 1.7.5
+ Flutter (or React Native) version:  Flutter 1.7.5
+ Testing Device/Simulator:  Physical devices
+ Screenshot issues (drag the file to attach here): 
![Screenshot_20200706-175349](https://user-images.githubusercontent.com/8816814/86593329-a1ed7880-bfb2-11ea-8e65-486474f4a52c.png)

**Comment by ameenbadri7** [comment]
We wanted to thank you for your patience during this busy time.
We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible, pls help to check our support policies on [this page](https://codecanyon.net/item/fluxstore-multi-vendor-flutter-ecommerce-full-app/25013325/support).

 
- The Registration is set as default Subscriber by woocommerce Rest API, you could try to customize this feature from the Rest API side.
 
- The push notification is working with our testing, please help to double-check the detailed guide
 

https://docs.inspireui.com/fluxstore/firebase/

please help to create a new ticket and link to this ticket if the problem is not solved - thank you for your time!

**Comment by GNAG1993** [comment]
@rushank did you get the issue resolved, as I'm facing the same issue.

**Comment by rushank** [comment]
@GNAG1993  Yes we have figure out on our way because their doc is not much very helpful. 
Are you using same package name or different package name ?

**Comment by GNAG1993** [comment]
@rushank I have changed the package name
I created Firebase and it started working properly now. they haven't provided any proper dedicate tutorial regarding creating database for Login, its confusing. Now i'm getting a new error: If a uses Login through SMS, app creates a new email ID for user which is lin format: countrycode-mobilenumber@domain, e.g. 91xxxxxxxxxx@xxxx.com
Did you got this type of issue?
