### ISSUE TITLE
App Store keeps rejecting FluxNews App: Guideline 4.2.2 - Design - Minimum Functionality

### ISSUE THREAD

**Issue by gunero** [inspireui/support#4193]
Step 1 (require): describe detail issues & screenshots

Detail Issues: My application keeps getting rejected from the App Store. Even tho everything is high quality and unique.
"Guideline 4.2.2 - Design - Minimum Functionality

We noticed that your app only includes links, images, or content aggregated from the Internet with limited or no native iOS functionality. Although this content may be curated from the web specifically for your users, since it does not sufficiently differ from a mobile web browsing experience, it is not appropriate for the App Store."

There are only three webview items in the application and the app has more than 70 other screens (posts and pages).

I was doing an appeal to get more information on why they rejected the application.

Here is what they answered:
"Thank you for your response. We appreciate your feedback, however, your app is not in compliance with the App Store Review Guidelines. To clarify, we found that your app does not include enough interactive functionality to be appropriate for the App Store. To resolve this issue, you may revise your app to include additional features that take advantage of the iOS platform and enhance the user experience."

Here is a video of the app:
https://youtu.be/EkVMUHHwuP0

Which "interactive functionality" (as described in their answer above) could I implement to get the app approved?

What can I add or do to make the app getting approved?

By the way, the app was successfully published on the Google Play Store.

**Comment by minhcasi** [comment]
@gunero - you could try to add the Apple login / Apple Pay to support as native ios app, don't try to add too much WebView as the quite strictly for the preview process - try to upgrade the looks and few more native-like, example some buttons should be persisted style, navigation should be used from Flutter (instead of simple navigate to webview)....

Please note that we may not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting. 

Hope you will success to pass the Apple review, good luck 😊
