### ISSUE TITLE
Internal error 500

### ISSUE THREAD

**Issue by sadeq90** [inspireui/support#4253]
Hi,
verifying ID from #3922

I am getting exactly the same error mentioned here
https://github.com/inspireui/support/issues/3805

I have disabled all plugins, and I found that once I enable MStore Api the issue occurs.
The issue occurs only when I switch the language to Arabic.
I am using WCFM and WPML
is there is any specific settings that I have to use for WPML?

Please advice.

**Comment by ameenbadri7** [comment]
Hello, @sadeq90 welcome back.

In order to run, WPML requires the following:
1. - WordPress 4.7 or later
2. - PHP 5.6 or above with memory limit of at least 128MB while 256MB is recommended (see WP memory settings). Keep in mind that the required memory for your site depends on your content, theme, and all plugins.
3. - MySQL 5.6 or above. Alternatively, you can use MariaDB 10.1 or greater.
4. - That you can create tables in your database.
5. - WordPress REST API must be enabled for WPML to function properly.
6. - Multibyte String extension for using WPML String Translation
7. - SimpleXML extension for using XLIFF files in WPML Translation Management.
8. - The eval() PHP function must be enabled. More about this in the section about eval().
9. - The libxml PHP Module 2.7.8 or higher

I guess `PHP memory limit` is your problem.

If those are ok with you and you have the same server requirement as those then let your host provider fix this issue, as it related to hosting issues and is not include from our support scope.
Pls, help to check our [support policies ](https://inspireui.com/support-policies).

Thank you.

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation.

Please help to create a new one and link it to this ticket if the problem is not solved.

thank you for your time ❤️
