### ISSUE TITLE
Fluxstore listing + fluxbuilder

### ISSUE THREAD

**Issue by thomasleroy80** [inspireui/support#4275]
Hello I manage a website with the listo theme.

I bought your system to create an app.

The concern is that I'm really bad at mobile APP, I can't install flutter.

And I think your listo theme solution will work with your FLUX BUILDER.

But no because I can't find the template in the preset templates

My question: do you offer help to build my app?

A developer asked me $ 1,500 for the configuration of your solution, it's not in my budget ...

Cordial thomas

**Comment by minhcasi** [comment]
@thomasleroy80 - thank you for the contact, could you give a tried with this app release from one of my client to see if you are happy with the same features - https://play.google.com/store/apps/details?id=com.dimsou.ukblackbiz&hl=en_US

Please send your detailed website to our support@inspireui.com - we will help to have a check and give some solution to release your app with a low cost, you could also consider purchasing the extended license to get more offer from our support team - https://inspireui.com/support-policies/

The latest Fluxbuilder is not supported Fluxlisting due to some incompatible config feature, but we could enable for this project on later versions.
Allow us to close the ticket as it is not related to the issue - thank you!

**Comment by thomasleroy80** [comment]
i have send email
