### ISSUE TITLE
Add a new tab on the tab bar when customer login

### ISSUE THREAD

**Issue by karmelcorn** [inspireui/support#4278]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I would like to add a new tab to the tabbar when customer login
+ Product & version: Fluxstore shopify 1.7.5
+ Flutter (or React Native) version: flutter
+ Testing Device/Simulator: IOS
+ Screenshot issues (drag the file to attach here): 

How can I add a new tab to show only information when a customer is logged in?

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**
#4243

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by ameenbadri7** [comment]
Please note that we may not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ 
- but we are trying to best to give extra miles with the supporting.

Since your requests are not related to bugs/errors/issues, 
You should upgrade your license to order a customization request so we serve your need to finish your project. 

Thank you.

**Comment by minhcasi** [comment]
@karmelcorn - pls try to customize the `tabbar.dart` to customize this feature - thank you!
