### ISSUE TITLE
Payment gateway on webview wont launch externall app on Fluxstore MV

### ISSUE THREAD

**Issue by djks74** [inspireui/support#4319]
I use payment gateway on webview, the picture showing that it wont launch to external app.
Looks like restriction or security problem?

Please help. Thanks.

From checkout then goes to webview
(https://user-images.githubusercontent.com/26361171/88197484-c319be80-cc6c-11ea-9fdc-823d67f34919.jpeg)

Then we choose for connect app
(https://user-images.githubusercontent.com/26361171/88197603-e7759b00-cc6c-11ea-9164-5f001ca1d2ae.jpeg)

After click Gopay to launch app, it showing this 
(https://user-images.githubusercontent.com/26361171/88197349-8a79e500-cc6c-11ea-94c6-7f80c3fa0864.jpeg)

**Comment by minhcasi** [comment]
@djks74 - you could use `https://pub.dev/packages/url_launcher` to open the Gopay. The current method is open the gojek inside the webview so that does not work. This feature will require some customization to custom the webview. Hope it help

Please note that we will not support answering or support technical issues for the regular license as per support policies - https://inspireui.com/support-policies/ - but we are trying to best to give extra miles with the supporting.
