### ISSUE TITLE
[FluxStore Woocommerce] 1.7.6 video in product description

### ISSUE THREAD

**Issue by altimimika** [inspireui/support#4331]
my issus  : 
video in product description Align to the right ...can you help me .. thank you
![124](https://user-images.githubusercontent.com/49140931/88279277-75449b00-ccec-11ea-97b0-847391e56ff6.jpg)

**Comment by ameenbadri7** [comment]
Your video is under the description area so its HTML web view, you cannot edit that.
We found that the best way to add a video to the fluxstore mobile app is to upload it inside the product gallery like that.
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/37524186/88339025-fa0dd400-cd41-11ea-9f8f-54de462f71f6.png">

To implement you will download the [YITH WooCommerce Featured Video
](https://arabic.mstore.io/wp-admin/plugin-install.php?tab=plugin-information&plugin=yith-woocommerce-featured-video&TB_iframe=true&width=600&height=550)

Then add your product video inside `Featured Video URL` option on woocommerce product general options.
<img width="957" alt="2" src="https://user-images.githubusercontent.com/37524186/88339338-8b7d4600-cd42-11ea-8b9b-324ffc849f3a.png">
**Don't forget to enable the ` "showVideo": true` from inside `lib\common\config\products.dart` file.**

BTW:  If you decide to embed the video to your app, it might not get the approval from AppStore and PlayStore due to their policy, this is My latest information about this feature maybe it changed!
Happy Coding!

Thank you.

**Comment by ameenbadri7** [comment]
I'm sorry to close this ticket as there is no response or active conversation. 

Please help to create a new one and link to this ticket if the problem is not solved. 

- Thank you for your time!
