### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cenkgulgun** [inspireui/support#4510]
![IMG_1364](https://user-images.githubusercontent.com/68585317/89636663-a2c74200-d8b1-11ea-8891-9c4ba9fcde26.jpg)

Android Studio Log

I/flutter (23839): [2020-08-07 10:20:48.120788Z][Fluxstore][AppState] build Theme

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Consumer<AppModel>(dirty, dependencies: [_InheritedProviderScope<AppModel>]):
The method '[]' was called on null.
Receiver: null
Tried calling: []("MainColor")

The relevant error-causing widget was: 
  Consumer<AppModel> file:///C:/Users/Cenk/Flutter/source/lib/app.dart:177:14
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      AppState.getTheme (package:fstore/app.dart:168:59)
#2      AppState.build.<anonymous closure> (package:fstore/app.dart:219:22)
#3      Consumer.buildWithChild (package:provider/src/consumer.dart:175:19)
#4      SingleChildStatelessWidget.build (package:nested/nested.dart:260:41)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by ameenbadri7** [comment]
You have a wrong config inside your `config_en.json ` file it happens when you try to config it manually,  try to use the awesome automatic [FluxBuilder](https://fluxbuilder.com/#download_section) to create the right config file.
If you still want to config it manually then try to make it like the original that you will find it inside `lib\config\config_en.json`

Thank you.

**Comment by minhcasi** [comment]
@cenkgulgun - pls help to comment your all issue into 1 open ticket #4495 - thank you for your time
