### ISSUE TITLE
Checkout page returning empty cart

### ISSUE THREAD

**Issue by tskmark** [inspireui/support#4541]
![9AEE766E-0E0A-453E-AB1A-470C37910696](https://user-images.githubusercontent.com/64660378/89737114-7f91c380-da66-11ea-9370-c7d1d7b0d917.jpeg)

**Comment by ameenbadri7** [comment]
Hi, @tskmark 
You can update to the latest fluxstore 1.7.6 and then but you checkout endpoint URL here inside 
`lib\common\config\payments.dart`

  ```
  "CheckoutPageSlug": "**checkout**",
CheckoutPageSlug must be the same in your website
```

Like if you have www.example.com/checkout-3
but the checkout-3 inside "checkout"

Thank you

**Comment by tskmark** [comment]
i'm using th latest version, upgraded by you support but i cant find ""CheckoutPageSlug": "checkout"
in payments.dart and my checkout url is "checkout"

**Comment by tskmark** [comment]
i'm using th latest version. do you mean, i add this "CheckoutPageSlug": "**checkout**",
CheckoutPageSlug must be the same in your website to payment.dart?

**Comment by ameenbadri7** [comment]
Yes you should add your checkout page slug inside it. By default its checkout but if you change it you should but it their.

let me know if you still have problems.

**Comment by tskmark** [comment]
I will try and get back to you, last one is there any way i can turn
iscaching on without re uploading the app?

**Comment by ameenbadri7** [comment]
@tskmark 
The only way I know is to rebuild again as you cannot upload the `lib\common\config\general.dart` like the config_en.json.

**FYI:**  
The purpose of `isCaching `is to optimize the user's performance by not reloading config again when experiencing the app. 
That's why when you enable `isCaching`, the product layout will not be loaded again. 
However, the `product detail screen` always needs to be `reloaded `due to special `data events`. 
Therefore, please consider using this feature if your site is mostly `"static"`. 
Otherwise, turn this one off if you need your data is always up-to-date.
Let me know if you still have any questions.
If you are looking to make the fluxstore faster you should optimize your website images and also upgrade your website toward performance by deleing the slow plugins you have on your website. 
we have dedicated documentation about performance you should look to it.
https://docs.inspireui.com/fluxstore/useful-tip/
https://docs.inspireui.com/fluxstore/performance/

Best!

**Comment by tskmark** [comment]
[Tue Aug 11 09:00:27.169093 2020] [php7:notice] [pid 29057] [client 197.210.44.23:56490] woocommerce_add_order_item_meta is deprecated since version 3.0.0! Use woocommerce_new_order_item instead., referer: https://miskayboutique.com/checkout/

**Comment by tskmark** [comment]
> [Tue Aug 11 09:00:27.169093 2020] [php7:notice] [pid 29057] [client 197.210.44.23:56490] woocommerce_add_order_item_meta is deprecated since version 3.0.0! Use woocommerce_new_order_item instead., referer: https://miskayboutique.com/checkout/
> 
> > <img alt="" height="14" src="https://camo.githubusercontent.com/bb425fd10b015b431794e52307d149f6a5bf6998/68747470733a2f2f69302e77702e636f6d2f6d69736b6179626f7574697175652e636f6d2f77702d636f6e74656e742f75706c6f6164732f323032302f30332f63726f707065642d637573746f6d2de280932d314033782e706e673f6669743d3139322532433139322673736c3d31"> Miskay Boutique**[Cart | Miskay Boutique](http://miskayboutique.com/cart/)**

The error

**Comment by codex-pro** [comment]
is your issue reolved?

**Comment by tskmark** [comment]
no

**Comment by codex-pro** [comment]
hey disbale quick checkout
