### ISSUE TITLE
I can't change the app bundle. it.s Error Messeage

### ISSUE THREAD

**Issue by TerWeWebStudio** [inspireui/support#4547]
I can't change the app bundle. it.s Error Messeage
How to Change ???

Fluxnews 1.4.1
Flutter 1.17.5
Testing Device/Simulator: Android Pixel 2 API 29
![Screenshot_3](https://user-images.githubusercontent.com/68330579/89783964-09628f00-db42-11ea-9b06-fb306f0599c7.png)
Thanks.

**Comment by ameenbadri7** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. 

To fix this you can search and replace for all file for the app bundle  `com.inspireui.fnews` to be your app bundle id `com.weweb.thaiinter` 
Because you only changed it in one place not all places.
refer to this link https://docs.inspireui.com/fluxnews/delivery/

Thank you for your time!

**Comment by TerWeWebStudio** [comment]
Where do I need to change the path files ?

**Comment by TerWeWebStudio** [comment]
I can fix it, thank you very much.
