### ISSUE TITLE
Customization Request

### ISSUE THREAD

**Issue by skalumek** [inspireui/support#4568]
Hello,
I would like to guidance on which files to change to achieve the below:
1. At the point of Checkout, i want to add 2 textboxes, that are editable, so i want to have the TOTAL field that is there, another editable field and third one that is a summation of Total and the second field.
2. At the product list where there is Add to Cart and Buy Now, I want to add another button for Share Now(instead of the one that is on the popup), I want to be able to share images of the item.

Advise if this is possible.

**Comment by minhcasi** [comment]
I'm sorry that we are not offered support to answer the technical questions due to the limit of scope support and the answer require to deeply check the coding solution (support policies https://inspireui.com/support-policies). 

Please help us to move your all question to the same open ticket support #4564 - thank you!

**Comment by skalumek** [comment]
Hi,
I was just asking which files to change and if such customisation is achievable
