### ISSUE TITLE
Compilation.

### ISSUE THREAD

**Issue by prophpgeek** [inspireui/support#4579]
Hi,
Do you provide app compilation service? If yes how can we do that? If now is there a resource you can point me to, that I can follow and setup Flutter and project and compile it.?

Thanks.

**Comment by minhcasi** [comment]
@prophpgeek - sorry we don't have this app - could you share some preference app on app stores so that we could have a check

**Comment by prophpgeek** [comment]
I am talking about fluxstore for multi vendor for woocommerce. I purchased
this day before yesterday.

**Comment by minhcasi** [comment]
@prophpgeek - please help to use this detailed document to set up the app - https://docs.inspireui.com/fluxstore

If you have any issues during using the app please share the detailed screenshot here so that the team could assist with the supporting, also help us to submit this form to verify the purchase code - http://verify.inspireui.com

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
