### ISSUE TITLE
Update Profile and Add new address

### ISSUE THREAD

**Issue by ap26091995** [inspireui/support#4609]
I want to add phone number field in update profile and want to edit and add new address when we view address in checkout.

**Comment by minhcasi** [comment]
@ap26091995 - thank you for the question. 

Due to the complexity of the e-commerce app, we have tried out best to release much functionality as much as possible but there are some small features that we could include in the release, feel free to change and customize the source code base on your requirements, you could use the Inspector Tools to customize any UI from the app - https://www.youtube.com/watch?v=yGMt3Y20Zmg
