### ISSUE TITLE
console issues in mstore-pro app

### ISSUE THREAD

**Issue by ManiSol9** [inspireui/support#4640]
I am not able to see console logs even I made useReactotron: false in mstore-pro app

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!


I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one with full information - thank you for your time!

**Comment by ManiSol9** [comment]
Actually i am working on mstore-pro react native moviel app which i purcahased last week

while i am running the react native project in my local meachine, i am not able to see the console logs.

Even i enabled the usb debugging mode but none of console logs are not coming.

**Comment by minhcasi** [comment]
@ManiSol9 - pls help to submit this form to verify your purchase - http://verify.inspireui.com

Thank you for your time

**Comment by minhcasi** [comment]
@ManiSol9 - sorry you have submited the wrong item - this product is not our product - https://tppr.me/j2hAW - thanks
