### ISSUE TITLE
TIckets not resolving problems (Fluxstore Woocommerce)

### ISSUE THREAD

**Issue by jakulz** [inspireui/support#4679]
I have been submitting tickets concerning some errors and suggestions from the support team are not resolving anything. Could you kindly assign someone to help through teamviewer or something. I desperately need help!!!

**Comment by minhcasi** [comment]
@jakulz - could you help to share your current screenshot issues? 

Sorry as limit with the Regular License, we are not offer to support for TeamView support http://inspireui.com/support-policies/ - please try your best and share your detail problems so that we could help to provide the solution, thank you for your time!

**Comment by minhcasi** [comment]
Hi sir, let us know if you have any update - thanks
