### ISSUE TITLE
Connecting to my own restful api(not prestashop api)

### ISSUE THREAD

**Issue by sushantmahajan85** [inspireui/support#4789]
i have just bought your prestashop fluxstore app
i have built my own website by using nodejs and mongoDb as the backend.
i want to make http get and post requests to my restful api and display data from my own api(endpoints)
But here prestashop api has already been set up. i want to replace it and use the data of my nodejs website.
if you can please guide me step by step, the procedure i need to follow to romove prestashop api and use my own api

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by sushantmahajan85** [comment]
i have submitted the form sir

**Comment by minhcasi** [comment]
@sushantmahajan85 - please try to customize the `services` and `models` folder to connect with your own API

<img width="635" alt="Screen Shot 2020-08-30 at 20 10 33" src="https://user-images.githubusercontent.com/1459805/91659892-dd14af80-eafc-11ea-9d1e-50bcb37c3f39.png">

In case you need to customize the UI, try to use the Inspector Tools - https://www.youtube.com/watch?v=yGMt3Y20Zmg

Due to some limit ò the Regular License https://inspireui.com/support-policies/ - we need not have answered the Technical Question, but we are trying our best to suggest some solution, hope it help.

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you for your time!
