### ISSUE TITLE
How can customer DEDUCTE his POINTS

### ISSUE THREAD

**Issue by bananweb** [inspireui/support#4832]
Hi, i use fluxstore on version 1.7.7
How can customer DEDUCTE his POINTS.
it is working fine on wordpress, but there is no option to apply it on app.
any suggetions ?

**Comment by minhcasi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FluxStore - how to change point with discount in cart ?](https://trello.com/c/uu3MWI6d/58-fluxstore-how-to-change-point-with-discount-in-cart)

**Comment by minhcasi** [comment]
@bananweb - this feature is not available and still in the team backlog for impelementing - we are working to upgrade it later - thanks

**Comment by minhtruong315** [comment]
Hi @bananweb I'm investigating to implement this feature. Can u send me admin account to login your website to check? via email: truong@inspireui.com
Can u help me record video in your website about "How can customer DEDUCTE his POINTS."?
Thanks

**Comment by bananweb** [comment]
@minhtruong315 i sent you 2 mails with details

**Comment by minhtruong315** [comment]
Hi @bananweb I haven't received any email. pls resend. thanks

**Comment by bananweb** [comment]
@minhtruong315 
is every thing is ok? i resent the mail again now from this mail abdelrahman.arafaa@gmail.com

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com 

Please help to move your next comment on the new support system (you could mention this ticket so that the team could know more about the ticket's history) - thank you for your time!
