### ISSUE TITLE
error with 'NativeOnePageCheckout' 

### ISSUE THREAD

**Issue by ahmed-foulad20** [inspireui/support#4858]
i have error when i disable NativeOnePageCheckout to make direct payment with credit card
its go to 404 page not found
![Screenshot_1599035008](https://user-images.githubusercontent.com/69421088/92099935-ce234b00-ede3-11ea-8863-d787113208c6.png)

ticket #4681

**Comment by ahmed-foulad20** [comment]
cash on delivery works ok

**Comment by ahmed-foulad20** [comment]
in this method the commented line show 404 not found page error 
if i change to other route its open the billing page
![Screenshot_1599128065](https://user-images.githubusercontent.com/69421088/92102562-725ac100-ede7-11ea-8f5b-f8aece13b4b6.png)

**Comment by ahmed-foulad20** [comment]
<img width="923" alt="Screen Shot 2020-09-03 at 10 05 57 AM" src="https://user-images.githubusercontent.com/69421088/92102600-7c7cbf80-ede7-11ea-8b3a-c6acad401429.png">

here is the code

**Comment by minhcasi** [comment]
You could try to change the slug that match with your checkout page 

<img width="1061" alt="Screen Shot 2020-09-03 at 17 58 57" src="https://user-images.githubusercontent.com/1459805/92106860-258ae080-ee0f-11ea-953f-7fdf5ac215c0.png">

**Comment by ahmed-foulad20** [comment]
its also same word checkout 
its work ok when enable NativeOnePageCheckout and go to billing page
but if i make it false its open 404 page

**Comment by minhcasi** [comment]
To fix the 404 issues when update `NativeOnePageCheckout: false` please try following solutions: 
**First solution:**
First, we need to create a page and name it "mstore-api" and remember don't set any parent page for it, then set page template to"page custom template
You need to install the mstore-api plugin at the first place.
Below is the screenshot for how to setting:

[img](https://blobscdn.gitbook.com/v0/b/gitbook-28427.appspot.com/o/assets%2F-LH63EuJG5iAEZIHCZ4d%2F-LH7kQXRhLdIHIgQy0NW%2F-LH7lTU197vsEPTKSJWh%2FScreen%20Shot%202018-07-11%20at%204.57.01%20PM.png?alt=media&token=54b834f1-3032-4c4a-9090-b251ddf7b5b9)

**Second solution:**
Copy the file "plugins/mstore-api/templates/mstore-api-template.php" to your current Wordpress template folder.
The same step-2 from the first solution above but select the "MStore Checkout" instead of "Page custom template" from the dropdown list, this naming could be changed from mstore-api-template.php file

**Comment by minhcasi** [comment]
Let us know your checking, thank you!

**Comment by ahmed-foulad20** [comment]
thanks bro first solution works ok
