### ISSUE TITLE
Issues with payment using razorpay.

### ISSUE THREAD

**Issue by midhun000** [inspireui/support#4876]
I have purchased Fluxstore pro and integrated it with the Magento server. When I try to checkout using Razorpay this error occurs. **Exception: Razorpay Error: Notice: Undefined index: additional_data in /var/www/html/magento/magento2-2.3/vendor/razorpay/magento/Model/PaymentMethod.php on line 223** 

![Screenshot_1599033207](https://user-images.githubusercontent.com/46200426/92208325-93371b00-eea8-11ea-853a-8760e4e0b025.png)

+ Product & version: 1.7.7
+ Flutter (or React Native) version:  1.20.2
+ Testing Device/Simulator:  Android Emulator (Pixel XL API 29)

Please help asap. Thanks.

**Comment by minhtruong315** [comment]
Hi @midhun000 for razorpay payment, I will research to implement OnePageCheckout to support this payment method.

**Comment by midhun000** [comment]
HI @minhtruong315  Any updates regarding these issues?

**Comment by minhtruong315** [comment]
@midhun000 This is hard feature. It needs more time to implement. I will investigate and update this feature later.

**Comment by midhun000** [comment]
I've solved the other two issues. So I updated the ticket.

**Comment by minhcasi** [comment]
Greetings from InspireUI 🎉
To improve user experience during support, we are announcing that a new ticket support system is available on this link https://support.inspireui.com 

Please help to move your next comment on the new support system (you could mention this ticket so that the team could know more about the ticket's history) - thank you for your time!
