### ISSUE TITLE
Problem the popup when u enter a post

### ISSUE THREAD

**Issue by sfiras** [inspireui/support#4903]
Hey there,

I'm facing this issue when I try to enter a post. it popups sometime and the app crash.
![Screen Shot 2020-09-06 at 10 31 27 AM](https://user-images.githubusercontent.com/70837127/92321857-0a4dea00-f036-11ea-974a-d6f9f5a6ece9.png)
![Screen Shot 2020-09-06 at 10 31 36 AM](https://user-images.githubusercontent.com/70837127/92321859-0c17ad80-f036-11ea-9b78-dc06cb33fed6.png)

also, I can see only part of my categories in the categories page.

Thank you in advance,
Firas

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user will use it for activation)

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by minhcasi** [comment]
@sfiras - could i confirm if your website is https://metukimil.co.il ?

Could you able to show the website data on the app home screen?

**Comment by sfiras** [comment]
Yes, the site is Hebrew Language, RTL , so i used the config for AR and i will translate it to Hebrew. if you can create the config for the Hebrew language will be Better.

here is my source code:
https://gofile.io/d/Pn9vJ5

**Comment by dttrung26** [comment]
Hi @sfiras ,
as I tested, your app is still running fine. Could you tell me a specific post/blog that leads to this issue? It would be much more convenient for us to deal with it. 
Have a great day.

**Comment by sfiras** [comment]
not true, it crashes after you enter some posts.
also, i told you that i cant see the whole categories in the site

**Comment by dttrung26** [comment]
Hi @sfiras , there are few things we need to clarify. 
1. The app could be crashed due to some external factors (lack of RAM, run out of memory, ...). And I said I tested your app already and it's still working fine. That's why I am asking for a specific case for another deeper test. What's I'm trying to do is solving the "blue screen" up there, where the issue root happens, not the app crash. 
2. If you can't point out the specific blog, please record me a video when it happens, and a console log as well.
3. We limited categories showed in category screen by 20 for better performance. If you want more, please go to `/lib/services/wordpress.dart` and modify 
```
    var response = await blogApi
          .getAsync("categories?per_page=enter-your-desired-categories-here&hide_empty=0&exclude=10");
```
in `Future<List<Category>> getCategories({lang = "en"})` function

Best!

**Comment by sfiras** [comment]
1. it seems that it back to work, good!
2. I still have some problem with the layout of the recipe (we are using wp
recipe maker plugin for some posts, the plugin not loading correctly in the
app) here is a link for the post inside the blog:
https://metukimil.co.il/2020/01/19/עוגת-לוטוס-גבינה-מעלפת/
and I attached some pictures to see how it looks in the app, could we work
to solve that problem, pls?
3. thanks a lot, it helped me a lot!
4. how can i set the default language only for Hebrew (i try to go after
the documentation but it's not so clear me because Hebrew is RTL) and
remove the option for other languages?

Thanks Again,
Firas

**Comment by dttrung26** [comment]
Hi @sfiras , 
for issue #2, this belongs to customizing request because FluxNews does not support for extra plugins that users installed in WordPress. According to our policies: https://inspireui.com/support-policies/, you could either request for an extended license or wait until more users wish to have this feature. At that time, we will consider update this free.
for issue #4, I've already taken a look at your project at it seems like you are using ar language and translate it as Hebrew. If so, setting ` "DefaultLanguage": "ar",` at `kAdvanceConfig`, located at `/lib/common/config.dart`would set Hebrew as default language. We will update the document for multi-languages support soon, so please stay tuned. 
In order to remove other languages at Language Screen, please go to your `/lib/common.tools.dart`. At `static Function getLanguagesList`, delete the language that you don't want. For example, deleting below code would remove English language.
```
 {
        "name": context != null ? S.of(context).english : "English",
        "icon": "assets/images/country/gb.png",
        "code": "en",
        "text": "English",
        "storeViewCode": ""
      },
```

Let me know if you still have any questions.
Happy coding!

**Comment by sfiras** [comment]
For issue number 1, could u please check for me how much it could cost to
make such a customize.

**Comment by dttrung26** [comment]
HI @sfiras ,
please refer https://inspireui.com/support-policies/ for Extended License. 
Best!

**Comment by dttrung26** [comment]
Closed due to no response from customer!
