### ISSUE TITLE
space between products and logo size

### ISSUE THREAD

**Issue by effec-tline** [inspireui/support#4909]
hey

we have 3 problems on this screenshoot

1 - the spaces between items 
2 - the space on the product page
3 - how change the size on the logo pic because its show very small and pic not this size

![3](https://user-images.githubusercontent.com/67228253/92348306-11770580-f0d3-11ea-9c34-1a83211719fb.png)
![1](https://user-images.githubusercontent.com/67228253/92348308-12a83280-f0d3-11ea-8f89-2c3eca221a75.png)

![2](https://user-images.githubusercontent.com/67228253/92348320-1a67d700-f0d3-11ea-9495-b18be79e909b.png)

Product & version: FluxStore 1.7.7

Testing Device/Simulator: android studio last version / simulator nexus 6

Step 2: Please verify license and sharing config files by submitting on this google form, http://verify.inspireui.com, (done )

**Comment by effec-tline** [comment]
any reply please?

**Comment by minhcasi** [comment]
Thank you for the questions:

1. you could update this config - https://tppr.me/IPFxr 
2. this bug is fixed on latest 1.7.7, please make sure to use this latest one
3. pls try to use Inspector Tool to customize the app UI - https://docs.inspireui.com/fluxstore/customization/

Please note that we may not answer the technical or integration question due to the limit of the Regular License support scope - https://inspireui.com/support-policies/ - thank you for your time!

**Comment by minhcasi** [comment]
Let us know your checking - thank you!
