### ISSUE TITLE
Fluxnews notification switch keeps turning on after restart the app

### ISSUE THREAD

**Issue by admincode1** [inspireui/support#4925]
Hello,

When switching the notification button off (from settings page) it keeps turning back on after restart the app. 

Fluxnews 1.4.3.

[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.20.1 at C:\flutter
    • Framework revision 2ae34518b8 (5 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\user\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\user\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • SM (mobile) android-arm64 • Android 10 (API 29)

• No issues found!

Thank you 😊

**Comment by minhcasi** [comment]
@admincode1 - note with investigating - thank you!

**Comment by dttrung26** [comment]
Hi @admin,
currently, FluxNews is using notification_permissions to handle this function. However, because of its limitation, the project could only open up the Notification Request Screen when permission is denied or unknown, and it couldn't if vice versa.
```
Note: if the permission is granted, this method will not do anything.
```
 Therefore, the only way to prevent the "Get Notification" button from being enabled in another session is going to Notification Request Screen and turning it off manually. For more information about how this plugin work, please refer https://pub.dev/packages/notification_permissions

**Comment by rmonst3r** [comment]
Hi Guys,

Does this mean that the notification toggle will not work until the Dart project fixes this?

**Comment by dttrung26** [comment]
Hi @rmonst3r , 
as I said, it could work. But if you need to turn it off, you need to disable the notification of FluxNews in devices manually. 
Best!

**Comment by admincode1** [comment]
@dttrung26
Thanks for your support 👍
