### ISSUE TITLE
Lots of problem 

### ISSUE THREAD

**Issue by muratosmanli** [inspireui/support#4946]
Hi we are taking this alert always

FAILURE: Build failed with an exception.

Where: Script ’/Users/muratosmanli/Developer/flutter/packages/flutter_tools/gradle/flutter.gradle’ line: 896
What went wrong: Execution failed for task ’:app:compileFlutterBuildRelease’. > Process ‘command ’/Users/muratosmanli/Developer/flutter/bin/flutter’’ finished with non-zero exit value 1
Try: Run with—stacktrace option to get the stack trace. Run with—info or—debug option to get more log output. Run with—scan to get full insights.

**Comment by dttrung26** [comment]
Hi @muratosmanli 
Please fill out the verification form in order to continue support services: https://verify.inspireui.com (please don't share the purchase code or screenshot public here as another user might use it for activation)

Your ticket will be closed after 24 hours if the verification form cannot be done. 
Best!

**Comment by minhcasi** [comment]
@muratosmanli - could you try to use some clean cache method - https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1 - also make sure to use the latest Flutter channel stable `flutter channel stable`

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
