### ISSUE TITLE
Disable all notifications and ads future, only need basic app

### ISSUE THREAD

**Issue by contactgvadevch** [inspireui/support#4983]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: Two days trying to find into your documentation a clear way to disable notifications and ads without crashing the builds. It looks like you force us using these futures by including them by default without no way get rid of them, and all are attached to your domain name and credentials. I only need a basic App, no notification, no ads. Can you please give me a clear way to remove them properly from the App . Thanks !!!
- [Is there a way to change the App ID/Logo at the beginning before customizing the App ? It crashed every time I attempt to change something ] first issue
- [ ] second issue
- [ ] third issue

+ Product & version: Fluxnews 1.4.3
+ Flutter (or React Native) version: Flutter 1.20.1
+ Testing Device/Simulator: Device iphone se 2nd gen / simulator iphone se 2nd / android simulator pixel 2 api 27
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on https://verify.inspireui.com **

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by dttrung26** [comment]
Hi @contactgvadevch , 
- in order to disable, open `/lib/common/config.dart`  and in `kAdConfig` ,  leave all variable with empty values except for `type`. Non-value key wouldn't trigger advertisement!
- in terms of notifications, currently FluxNews is using Firebase Cloud Message/ One Signal to implement this feature. Therefore, notifications would be disabled as default if you haven't touched the configuration for those features. 
- Your app crash might be a result of multiple external factors such as lack of RAM, shortage memory, ... FluxNews has no reason in causing crash your app because it has been tested already. Please try your Flutter SDK setup with https://flutter.dev/docs/get-started/test-drive

**Comment by dttrung26** [comment]
Close due to no response from customer.
