### ISSUE TITLE
Problems logging in

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/support#4999]
Fluxstore Version: 1.7.7
Flutter : v1.20.3

1- windows 10 android studio - Android emulator
**I have another question. I've done everything but an error appears**
![93015547-151ef680-f5c3-11ea-9da3-e853bb303497](https://user-images.githubusercontent.com/54249914/93077216-2cc4b080-f691-11ea-96e3-e6aedd4487d4.png)

---

**2- macos xcode - iphone x** 
**login  google account & facebook he is working well**
**There is a problem in using Apple ID and SMS**
_I followed the instructions as in the video_
![22](https://user-images.githubusercontent.com/54249914/93077909-3864a700-f692-11ea-821c-996b39b61eba.PNG)

**Comment by minhcasi** [comment]
Please follow strictly the official documentation ( https://medium.com/@inspireui/setup-google-login-for-flutter-apps-fedc58a490b8)
If fail please double-check these solutions:

In the beginning the main problem will face a lot of you is that you are getting the wrong SHA1 & SHA256 code!
When you use this code for example: keytool -list -v -keystore C:\Users\MG\Desktop\test.jks -alias test
it will show the current code not the code which the app build with, so I recorded a video for the full solution to fix that and the common problem will be caused by Facebook as well!
Here's the video with English subtitle: https://www.youtube.com/watch?v=spC-CJzlno4 🎥

The second problem, that Firebase doesn't support the old Google Play services on the phones, that means you need to update it by following these steps from your smartphone: Settings > Apps > Apps > Google Play services > App Details then check for updates - https://tppr.me/k9eEg
For Huawei, I solved the problem by downloading the update manually from here: https://www.apkmirror.com/apk/google-inc/google-play-services/

**Comment by haidarsalim** [comment]
I am still facing a problem on the iPhone @minhcasi 
There is a problem in using Apple ID and SMS
![Screen Shot 2020-09-14 at 4 39 44 PM](https://user-images.githubusercontent.com/54249914/93149265-b6cd4300-f6aa-11ea-8868-40396a6bf6ea.png)

**Comment by minhcasi** [comment]
@haidarsalim - pls check some note for the apple login on this link https://docs.inspireui.com/fluxstore/sign-in/#4-apple-sign-in - you could only test it on real device, on iphone simulator it will not work

**Comment by haidarsalim** [comment]
Ok i will disable apple id
Google Account login service works
But using SMS does not work
You have done everything

**Comment by minhcasi** [comment]
@haidarsalim - pls help to check this video guide that could help: https://www.youtube.com/watch?v=3NLP-1KX_Vk

some useful links:
- https://medium.com/@fayaz07/firebase-phone-auth-with-flutter-db7e934ef46f
- https://firebase.flutter.dev/docs/auth/phone/
