### ISSUE TITLE
how to connect the mobile categories to web categories 

### ISSUE THREAD

**Issue by alaradi2006** [inspireui/support#55]
**Mandatory Info (please complete the following information):**
 - Product: [e.g. MStore, ListApp]
 - Your Purchased Code: [get from https://codecanyon.net/downloads]
(we may not reply if you are not our customer)
a9c6782d-8c5d-4811-8c4a-2ccc9d6be005 mstore multivendor
**Describe the issues**
how to connect mobile categories to web categories 
**Screenshots**

**Additional context**
Add any other detail logs about the problem here.

**Comment by minhcasi** [comment]
Hi there, please note some info below:
- The categories are fetched automatically, but at the Homepage, you need to config the Horizontal config from the common/config.js file 
- Please create 1 ticket for your all issues that help to team focus on your issues, instead of creating many tickets at the same time.
- Any "How to", "customization" questions may not get the response as it related to the customization / modify the product which is not on support scope, please help to check the License https://codecanyon.net/page/item_support_policy
- We have closed other ticket and combine to this ONE ticket:
https://github.com/inspireui/support/issues/57
https://github.com/inspireui/support/issues/58
https://github.com/inspireui/support/issues/54
https://github.com/inspireui/support/issues/53
https://github.com/inspireui/support/issues/52
