### ISSUE TITLE
[ListPro] Unable to Load Images and listing in the app

### ISSUE THREAD

**Issue by anwark** [inspireui/support#592]
**Required Info (please complete the following information):**
 - Product: ListPro
 - Your Purchased Code: ae03d146-d1ca-4017-85e6-98303d17fb33

**Describe the bug**
In the app, there are no Images for listing and in the list, there is no listing visible 

**Screenshots**

![Uploading no_Image.png…]()

**Additional context**
Please tell me how I can send a push notification 
If possible please share your config.js that use for the app setting

**Comment by thangvo9x** [comment]
Hi. Can you share AppConfig.json with us? I can't view your screenshots, send it again
Thanks

**Comment by anwark** [comment]
Please find all from here - http://creativemediafx.com/SA/appConfig.zip
and please guide me on how to use Wp-admin to manage app

**Comment by thangvo9x** [comment]
Hi. I Checked your source. You must have to map to categories on your website. So that, 
edit in App/common/config/index.js & find this section 
change category -> your id categories on your website 
<img width="800" alt="Screen Shot 2019-05-20 at 10 10 12 AM" src="https://user-images.githubusercontent.com/23457178/57994494-a4a7b880-7ae7-11e9-9d27-01f517628ad7.png">
then your listings will be displayed.

**Comment by minhcasi** [comment]
Duplicate of #606

**Comment by anwark** [comment]
i update the LIstings but still Images not visible and side menu also not visible 
![2019-05-24_1555](https://user-images.githubusercontent.com/109449/58322957-29743880-7e40-11e9-8afb-a3af682ed40c.png)
