### ISSUE TITLE
[Mstore Opencart] currency not changing after changing from profile

### ISSUE THREAD

**Issue by trippynash** [inspireui/support#637]
Hi,

I've been working on currency change and it seems it doesn't change even after you change it from the settings. All the product have $ instead of INR/Rs. Please add a fix to this issue ASAP.

**Comment by minhcasi** [comment]
Hi, could you help to share the screenshot on both mobile and the website setting for this issue - thank you!

**Comment by trippynash** [comment]
![Screenshot_2019-05-24-17-46-27-95_f73b71075b1de7323614b647fe394240 1](https://user-images.githubusercontent.com/46844686/58327087-4f073f00-7e4c-11e9-86a0-05fa792bb07e.png)
![Screenshot_2019-05-24-17-46-37-79_f73b71075b1de7323614b647fe394240 1](https://user-images.githubusercontent.com/46844686/58327114-634b3c00-7e4c-11e9-8fda-1e99a9d2061b.png)
![Screenshot_2019-05-24-17-50-50-45_f73b71075b1de7323614b647fe394240 1](https://user-images.githubusercontent.com/46844686/58327164-84139180-7e4c-11e9-84c8-ae892a35b35e.png)


Please check the list of screenshots. As you can see being the Currency as INR, it shows $ in product prices.

**Comment by trippynash** [comment]
In addition to that, in Horizontal Layout, Categories name is not showing in the horizontal section, only Show All option is showing.After i changed the layout config from ceBuilder, this problem occurred.
Please refer first image.

**Comment by minhcasi** [comment]
Could you help to attach the config files (common/config.js and appConfig.json) here - we will help for checking and resolve above missing image - thanks

**Comment by trippynash** [comment]
[common.zip](https://github.com/inspireui/support/files/3220066/common.zip)

Files Added As per your requirement. Currency converter is kind of a priority. - Thanks

**Comment by minhcasi** [comment]
@minhtruong315  - pls help to  check and suggest a solution - thanks

**Comment by trippynash** [comment]
Need Urgent help. Please respond.

**Comment by minhcasi** [comment]
Hi @trippynash 

Sorry for the lated response, could you help to open the common/config.js file and change the default currency and country code for the app:

<img width="762" alt="Screen Shot 2019-05-31 at 9 57 15 AM" src="https://user-images.githubusercontent.com/1459805/58678617-9a5ca880-838a-11e9-8fcf-80abde091b3c.png">

We may remove the currency switcher from the profile setting and it's wrong design due to the currency should come with the "exchange rate" which is quite complex and require the API. So far, let try with the default setting from the app
