### ISSUE TITLE
[CeBuilder] - problem build android v

### ISSUE THREAD

**Issue by raiedahmed** [inspireui/support#639]
Cebuilder

https://ibb.co/2hzVhHk
expo build:android

https://ibb.co/pnxrgwX

expo start and expo build:android

https://ibb.co/H4c5Kk2

**Comment by minhcasi** [comment]
Hi, please try to check these solution:
1. There are both beonews-expo and beonews-pro folder, pls make sure to open these folders instead of the root folder.
2. Try to run the project on C: hard drive and after unzip the download folder.
3. Please make sure to use the latest CeBuilder from - https://github.com/inspireui/cebuilder/releases

Let us know your checking
