### ISSUE TITLE
ListApp questions

### ISSUE THREAD

**Issue by Pars1vaLl** [inspireui/support#640]
- Product:  ListApp

Hi team, I have couple questions:

1. What is the best hosting for ListApp? Any recommendations?
2. Is it possible to use any caching plugin for the App? It reloads again everytime I restart the app.
3. Where is your hosting located? Because Apps performance is really slow for me.
4. What if I use CDN? Will the App work faster?

Thanks

**Comment by thangvo9x** [comment]
1. What is the best hosting for ListApp? Any recommendations?
=> Should be a VPS. or if you choose a hosting, should be apache server.
2. Is it possible to use any caching plugin for the App? It reloads again every time I restart the app.
=> Yes. But these plugins can affect your app. sometimes, the app will get from old data.
3. Where is your hosting located? Because Apps performance is really slow for me.
=> The our server is from Digital Ocean.
4. What if I use CDN? Will the App work faster?
=> Of course.
