### ISSUE TITLE
ListApp - Map view listings

### ISSUE THREAD

**Issue by bfwi410a** [inspireui/support#693]
Hi,
on map view android and iOS shows different listings. In iOS only 10 and in android nearly all. Why the different? Two questions:

1. Is it poissible to show all listings on map view in iOS as well as android?
2. Is there any solution to implement sort order? First paid listings from a special category or listing type and than the other listing.

[AppConfig.zip](https://github.com/inspireui/support/files/3275530/AppConfig.zip)
![Map](https://user-images.githubusercontent.com/1284361/59257627-96f0d900-8c36-11e9-8098-c939dad484c5.jpg)
![2019-06-11 10_50_15-Window](https://user-images.githubusercontent.com/1284361/59257718-c4d61d80-8c36-11e9-927c-0526a95e8e9f.png)

**Comment by thangvo9x** [comment]
Hi. 
1. Is it poissible to show all listings on the map view in iOS as well as android?
=> No. It isn't. There are some points different in iOS as Android. You can edit it from Config/index.js to change Zoom of Map. And We can't show all because the problem was related to performance.
2. Is there any solution to implement sort order? First paid listings from a special category or listing type and than the other listing.
=> No. There isn't. But we'll integrate it in the next version.
