### ISSUE TITLE
mstore pro 3.9.1 - a cant start app in simulator

### ISSUE THREAD

**Issue by stanojeviclive** [inspireui/support#768]
Hi,
I can't start app on iOS simulator. I was waiting 2 hours and nothing happend.
![mstorepro1](https://user-images.githubusercontent.com/29498719/60833759-4d58c700-a1bf-11e9-9290-8a48dbf27726.jpg)
![mstorepro2](https://user-images.githubusercontent.com/29498719/60833770-53e73e80-a1bf-11e9-8a79-f62c532d3df4.jpg)

**Comment by minhcasi** [comment]
Hi, could you help to download the latest version 3.9.2 to fix the issues (please open one of the mstore-pro or the mstore-expo, instead of opening the root folder)

If the process from Cebuilder not work, please try with a terminal with: yarn install && yarn start

I'm sorry for the lated response as missed the ticket
Thank you!
