### ISSUE TITLE
Fluxstore 

### ISSUE THREAD

**Issue by andersonsoares12** [inspireui/support#809]
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: eda53d77f61dde3c)
Crash report written to /Users/andersonsoares/Documents/FluxStore-woo 1.3.0/source/flutter_07.log;

**Comment by minhcasi** [comment]
Hi, could you help attache you purchase screenshot from https://codecanyon.net/downloads to verify your purchase - then reopen the ticket.

Also take the screenshot of issues so that we could know the root cause, try to upgrade to flutter 1.7 by using "flutter upgrade", delete the Pod file and run "flutter run" again
