### ISSUE TITLE
[MyList App] -  No left Menu

### ISSUE THREAD

**Issue by kwsystems** [inspireui/support#818]
1. My issue
I can't see the left Menu on the app

2. Screenshots
https://www.dropbox.com/sh/zats9npn6uvohca/AACbQylcoMr4CwJPMy5_EJJ6a?dl=0

3. My screenshot of the purchase product or my comment:
https://www.dropbox.com/s/5y6wqwy0m9e7br0/Screen%20Shot%202019-07-14%20at%209.52.56%20PM.png?dl=0

**Comment by minhcasi** [comment]
Try to open your all ticket to one issue - thanks

These issues are closed
https://github.com/inspireui/support/issues/819
https://github.com/inspireui/support/issues/820
https://github.com/inspireui/support/issues/821
https://github.com/inspireui/support/issues/822

**Comment by kwsystems** [comment]
Should I post them again??

**Comment by kwsystems** [comment]
**My issue #1** 
I can't see the left Menu on the app

Screenshots
https://www.dropbox.com/sh/zats9npn6uvohca/AACbQylcoMr4CwJPMy5_EJJ6a?dl=0

My screenshot of the purchase product or my comment:
https://www.dropbox.com/s/5y6wqwy0m9e7br0/Screen%20Shot%202019-07-14%20at%209.52.56%20PM.png?dl=0


**My issue #2** 
Can't change text on user details:
Contact and About Us

Screenshots
https://www.dropbox.com/sh/ofs89p0g3tzveit/AAA1AUIQeV2AHRm8B9hsC9O3a?dl=0

My screenshot of the purchase product or my comment:
https://www.dropbox.com/s/5y6wqwy0m9e7br0/Screen%20Shot%202019-07-14%20at%209.52.56%20PM.png?dl=0


**My issue #3** 

Address doesn't appear on listing when I clicked is also null

Screenshots
https://www.dropbox.com/sh/aaxhm25z7hl5r44/AABh_LA0N8w7-wmRaZR4PN3Ia?dl=0

My screenshot of the purchase product or my comment:
https://www.dropbox.com/s/5y6wqwy0m9e7br0/Screen%20Shot%202019-07-14%20at%209.52.56%20PM.png?dl=0



**My issue #4** 

Change Get Directions to another language

Screenshots
https://www.dropbox.com/sh/3lcj43p6uimzh9x/AAB5tCaeiUS2IWCxCiWkQbWya?dl=0


**More issues** 

5) Instead of the name is showing the email.
6) When Listing a new one the google maps api doesnt work here
7) I can't post any listing
8) I want to add the social media buttons here.
9) Review doesnt show correctly

Screenshots:

5) https://www.dropbox.com/s/nlllah1a8jy4bgy/1.jpg?dl=0
6) https://www.dropbox.com/s/8o6gl8cp2z082g8/2.jpg?dl=0
7) https://www.dropbox.com/s/0226216b5dsebn5/3.PNG?dl=0
8) https://www.dropbox.com/s/p2z19dfddtdg1ku/4.jpg?dl=0
9) https://www.dropbox.com/s/dgri3ftudy7yiil/5.jpg?dl=0

My screenshot of the purchase product or my comment:
https://www.dropbox.com/s/5y6wqwy0m9e7br0/Screen%20Shot%202019-07-14%20at%209.52.56%20PM.png?dl=0

**Comment by thangvo9x** [comment]
Hi bro. Could you share your AppConfig.json file? Which language are you using on your mobile app?

**Comment by kwsystems** [comment]
Here you go!
I have 3 languages and I put spanish as the main one.

[AppConfig.json.zip](https://github.com/inspireui/support/files/3427588/AppConfig.json.zip)

**Comment by kwsystems** [comment]
Any news?

**Comment by kwsystems** [comment]
You made me close the others and put everything in one and you don’t answer....

**Comment by kwsystems** [comment]
@thangvo9x  any news?

**Comment by thangvo9x** [comment]
Hi. We're on some off days at the weekend.
1. The menu is still working. 
<img width="489" alt="Screen Shot 2019-07-29 at 9 47 27 AM" src="https://user-images.githubusercontent.com/23457178/62018682-eccd1080-b1e5-11e9-9698-94e58bab1446.png">
Please double-check.
2. You could change it in Languages.js or if it hasn't changed. so you're gonna Config/index.js and change it here.
3. the slug theme in AppConfig.json is "myListing" not "mylisting".
4. Change text at Components/Detail/ListingData/index.js
5. Instead of the name is showing the email. => Just only update the account information.
6. When Listing a new one the google maps app doesn't work here.=> give me an account for double-checking on your website.
7. I can't post any listing => Please config follow steps here to post a new listing.
https://docs.inspireui.com/listapp/getting-started/#jwt-authentication
8. I want to add the social media buttons here. => You must customize it. it is out of scope from supporting. Hope you see. 
9. Review doesn't show correctly => same 6.
Thanks
