### ISSUE TITLE
[msstore] I have a few questions

### ISSUE THREAD

**Issue by saeidAalizade** [inspireui/support#844]
Purchase codes 
153bb1ff-3f3e-41cd-a219-da061397aef5

1- How can I connect the news section to the subdomain?
Example : domain.com/blog
That is, we have a WordPress and we've implemented it in the subdomain and we want to read the application's news section from the subdomain.

2-The shipping section is active on WordPress, but not in the app

3- How can I change the Webview font and rtl?

**Comment by minhcasi** [comment]
1. it's may not work as domain.com/blog because of it cause in-correct Api endpoint, please use blog.domain.com or create other subdomain link to your site (use for mobile app only)

2. There is the zone config file (default is the first zone - zoneId: 1), this could cause the missing shipping on your site, please try to change to your own zone id.

3. Update the components/Webview/index.js or webview.js - you can add new custom font style 

Thank you!

**Comment by saeidAalizade** [comment]
hello,

1.How can I do this? (In app codes)

2.fixed. But it has a problem 
My website has two shipping method, one is Free shipping and second is Flat rate. If Total amount is more then 50$ the Free Shipping method apply otherwise Flat Rate apply. But this is not working in app. How can I do this without user selection?

3.Do I have to css?

Thanks

**Comment by minhcasi** [comment]
1. First you need to create new subdomain on your domain provider (ex Godaddy) and point to your hosting server, from the hosting side add new virtual host config for the webserver to update it.

3. You can check this guide - https://github.com/archriss/react-native-render-html - thank you!
