### ISSUE TITLE
[ListPro] - Comprehensive Revision Request 

### ISSUE THREAD

**Issue by theAlinux** [inspireui/support#845]
Hi;
Do you customization, if yes i will write the list or do you as special (will i post mail, message etc.)?

**Comment by thangvo9x** [comment]
send email to support@inspireui.com Thanks

**Comment by theAlinux** [comment]
config file => #515 

but just "local enable: true" doesn't work from me so i return to it "true", now get data from wordpress, why did happen it i don't know,

i found a few bugs,
1- login as normal return the success message but don't auth.
2- as social login return success message but not get user info 

![unnamed](https://user-images.githubusercontent.com/10341948/62422886-4b046280-b6c2-11e9-9401-ce2034fa718d.png)

3- select category to new list add get error

![unnamed (1)](https://user-images.githubusercontent.com/10341948/62422892-5ce60580-b6c2-11e9-9169-e918f70c52dc.png)

and my revision requests

1- title "What can we help you find" i want to changeable on wordpress and same search placeholder "Ex.Food service, bar, hotel,..." and same "Wish List"
2- remove open the app first, intro (travel)
3- booking system want to paid, isn't there free version?
4- mobile app my listing doens't work, i added listing but does not seem to the app

purchase code => 8d58d69e-b9c6-40fe-a0c8-c5c7b7ab2d6a

please, asap solution

**Comment by theAlinux** [comment]
@thangvo9x ???

**Comment by minhcasi** [comment]
As your per requests

1. This could be changed from the common/appconfig.json file
2. This could custom the navigation/index.js to reorder the tab navigation
3. This option could be enabled from the config.js file to support the booking, but the current Listing is not integrated with the WooCommerce so this feature will not work completely 
4. Could you check if the new listing appears from the website? Otherwise, check the to see if this plugin is work correctly - https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/

**Comment by theAlinux** [comment]
I want to link headers to wordpress

**Comment by minhcasi** [comment]
Hi, pls check the example #3 to display the news layout - https://docs.inspireui.com/listpro/theme/

**Comment by theAlinux** [comment]
@minhcasi 
okay but now all of textarea are remove after than i change the textareas in listapp manager settings, why?
