### ISSUE TITLE
[mstore multivendor] Can I use the Mstore Multi Vendor App just as a Wordpress site?

### ISSUE THREAD

**Issue by agriffyn** [inspireui/support#92]
I have purchased the Mstore Multi Vendor app for IOS and saw that there was a wordpress backend. Is it possible to run this app just as a wordpress site? If so how do I go about doing so? Thank you so much!

**Comment by agriffyn** [comment]
Thanks for the reply Levi! Would the mobile site look and function the same as the what the app would?

**Comment by levi-beers** [comment]
For the most part yes. If someone is visiting the site from a mobile browser (Safari, Mobile Chrome, etc) they would see http://dokan.mstore.io/ (the demo website). With mobile browser, rendering is done entirely by the browser. The mobile app looks a little different because the product data is pulled via WooCommerce's API and rendered with native code.

**Comment by levi-beers** [comment]
Here, you can see how the multi-vendor app would look on [Android](https://play.google.com/store/apps/details?id=inspireui.mstore.multi.vendor&hl=en_US) and iOS. Note: InspireUI does not have a demo of the iOS version because Apple doesn't permit "demo" applications. If you look at the Android screenshots, iOS looks very similar if not identical in most aspects.

**Comment by agriffyn** [comment]
Hi Levi, thanks for the response again. I meant if I just set it up as a wordpress site without making it into the app would mobile safari (on iphones) look like those screenshots of the app?

**Comment by agriffyn** [comment]
Hi Levi, sorry to bother you I was just wondering  if I just set it up as a wordpress site without making it into the app would mobile safari (on iphones) look like those screenshots of the app?
