### ISSUE TITLE
[FLuxstore PRO] Payment Gateway issue

### ISSUE THREAD

**Issue by samik9** [inspireui/support#941]
Hello guys, I been struggling a lot with the payment gateways, I got the ID`s from wp-json/wc/v2/payment_gateways  but when I try to pay with **epayco** and **payulatam** the web view takes me to and 404 page, 

Video: https://d.pr/v/UqutmO
Config File: https://d.pr/f/3728tq

**Comment by minhcasi** [comment]
### First solution:

First, we need to create a page and name it "mstore-checkout" and remember don't set any parent page for it, then set page template to"page custom template
You need to install the mstore-checkout plugin at the first place.
Below is the screenshot for how to setting:

<img width="853" alt="assets_-LH63EuJG5iAEZIHCZ4d_-LH7kQXRhLdIHIgQy0NW_-LH7lTU197vsEPTKSJWh_Screen Shot 2018-07-11 at 4 57 01 PM" src="https://user-images.githubusercontent.com/1459805/63221562-22519200-c1c5-11e9-8c30-a0c8c16aecfa.png">


###Second solution:

Copy the file "plugins/mstore-checkout/templates/mstore-checkout-template.php" to your current Wordpress template folder.
The same step-2 from the first solution above but select the "MStore Checkout" instead of "Page custom template" from the dropdown list, this naming could be changed from mstore-checkout-template.php file

**Comment by samik9** [comment]
Hi @minhcasi I followed the **first solution** as you mentioned, everything works fine, but when the webview loads shows checkout web and after some seconds, it goes white, nothing happens, only white screen please check video https://d.pr/v/Wcx25A



<img width="1055" alt="Captura de Pantalla 2019-08-18 a la(s) 3 27 45 a  m" src="https://user-images.githubusercontent.com/50071744/63222076-2ef3cd00-c168-11e9-94ac-1e7c4f61720d.png">

**Comment by samik9** [comment]
I test it on the website directly and useing this Mstore checkout, only loads a white screen

**Comment by samik9** [comment]
@minhcasi can you please help me out? Is there any solution in progress for other payment methods en general?  I been trying to make this work for days, thank you for your time

**Comment by minhcasi** [comment]
Hi @samik9  - please help to try the second solution above, the template should be loaded from "plugins/mstore-checkout/templates/mstore-checkout-template.php", so it could be copied manually to your active theme - this is the form when handling the payment via Webview. Let me know your checking, thank you!

**Comment by samik9** [comment]
@minhcasi  thank you for your answer, I followed the second solution, but the only thing i got is this screen video: https://d.pr/v/o5LvIl

Instead of load the webview checkout page, shows and empty cart page, can you please check my wp settings?

**Comment by minhcasi** [comment]
I got the issue, let us have a check and let you know

**Comment by minhtruong315** [comment]
Hi @samik9 How to checkout in website? payment gateway must work in website the first.

**Comment by samik9** [comment]
@minhcasi yes, is because im using default template, i will use the other now

**Comment by samik9** [comment]
@minhtruong315 check again

**Comment by samik9** [comment]
can i send you an email with my ftp and admin login for wp?

**Comment by minhtruong315** [comment]
<img width="1358" alt="Screen Shot 2019-08-21 at 14 33 11" src="https://user-images.githubusercontent.com/10402500/63411859-a6538600-c420-11e9-9452-88b3b6692324.png">
I don't see any products

**Comment by samik9** [comment]
The path for the shop page is https://gzo.io/buganbillia/tienda/ @minhtruong315

**Comment by minhtruong315** [comment]
Can you send me account to login to admin panel via email truong@inspireui.com

**Comment by samik9** [comment]
@minhtruong315 sent!

**Comment by minhtruong315** [comment]
@samik9 pls check app again. it is working well

**Comment by samik9** [comment]
Hi @minhtruong315 

I noticed that you closed the ticked but now the only screen a got in checkout is: Invalid authentication cookie. Please try to login again. Video:  https://d.pr/v/tSBttS
This happens when **"GuestCheckout": true**, on cofing.dart  

Now when **"GuestCheckout": false**, everything works well but when I click on **ePayco** to make the purchase, it takes me to the webview **BUT** it autoselect **"cash on delivery"** Video: https://d.pr/v/umUbIP
