### ISSUE TITLE
[ListApp] - Cannot init app via CEBuilder 

### ISSUE THREAD

**Issue by dxpsite** [inspireui/support#956]
```
yarn install v1.17.3
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning expo > fbemitter > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by minhcasi** [comment]
Hi, could you help to share your purchased product screenshot, thank you!

**Comment by dxpsite** [comment]
Its solved. Simply install windows GIT

**Comment by storchaktitos** [comment]
**exactly the same situation. tried everything...** (((((

`yarn install v1.17.3
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning expo > fbemitter > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**CEBuilder**
STEP 2
All Good !
Please read the document to install all required plugins, if all good then you can go to Customization tab to custom the app.
Powershell5
Chocolatey
NodeJSv12.10.0
Yarn1.17.3
Expo3.0.10

**Comment by dxpsite** [comment]
> 
> 
> **exactly the same situation. tried everything...** (((((
> 
> `yarn install v1.17.3 info No lockfile found. warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json. [1/4] Resolving packages... warning expo > fbemitter > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2. error Couldn't find the binary git info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`
> 
> **CEBuilder**
> STEP 2
> All Good !
> Please read the document to install all required plugins, if all good then you can go to Customization tab to custom the app.
> Powershell5
> Chocolatey
> NodeJSv12.10.0
> Yarn1.17.3
> Expo3.0.10
> 
> CeBuilder.Setup.0.35.0
> Git-2.23.0-64-bit
> node-v12.6.0-x64
> yarn-1.17.3

simply install from there https://git-scm.com/download/win (if you are Win-user). This problem about system PATH
